### ISSUE TITLE
"Night Tours" park policy...

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#100]
Split out from #65 : 

> dymanoid: Bed time --> drastically less visitors everywhere. No special handling for the tours currently.

I set a few parks to "night tours" and set night speed to slow to observe what happened more closely. It looks like not much is happening.

As far as I can tell, the only effect the policy has in vanilla is to increase park revenue during nighttime hours (or possibly it doesn't even go that far and just adds 20% extra revenue per week or something)?

I was wondering if RT could do a better job, and actually send some people to the parks at night (eg. maybe people on the evening shift, and some tourists)?

**Comment by dymanoid** [comment]
**Real Time** currently doesn't respect this policy at all. It may be well combined with #86.
