### ISSUE TITLE
Outside connection traffic dependent on time of day

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#101]
Split out from #65:

> Almost certainly outside scope of RT

In sleep time, I'd expect traffic from outside road and rail connections to change...

* Fewer passenger trains
    * half usual rate? 
    * could potentially be achieved by turning off rail buildings at night (like service buildings idea mentioned above)?
* More freight trains
    * taking advantage of quiet rail network to import/export goods
* Fewer immigrants, tourists via roads
    * because most people are sleeping
* More goods/industry vehicles
    * taking advantage of less congestion at night for more efficient deliveries
* Less dummy traffic
    * industry and goods vehicles might increase though

Ideally a gradual transition - period defined by existing `overtime` setting?

**Comment by Sipke82** [comment]
I kinda disagree, with the more cargo transport. while i think there should still be some cargo transport, it should be considerable less. a larger number of the drivers will be sleeping too! When i drive at night i often see lots of parking lots near the highway, full of sleeping truckdrivers.

Instead it would be cool if trucks would seek out for a parking spot at 11 pm.... to park there until like 6 AM?

**Comment by dymanoid** [comment]
This mostly affects economy, so out of scope.
The only two points that can be implemented in **Real Time** from my point of view:

- dummy traffic (affects nothing, just visual)
- tourists (they're already managed by **Real Time**, so why not manage their spawn time?)

**Comment by aubergine10** [comment]
Dummy traffic and tourists would suffice IMO - it's just to give a visual sense of the highways being quieter in the early hours of morning - again, reinforcing the notion of real time.

As people could be driving from distant cities, it would be ideal if traffic could taper off to a trickle in the early hours of the morning (2-3am) and then start picking up again around 5-6am.

It would be nice it traffic in/out of the city could show some peaks and troughs not just at certain times, but also certain days of week. For example, there could be an influx of tourists on Friday evening with people coming to the city for the weekend, and they'd leave on Sunday evening.

I doubt it's possible, but it would be awesome if there was business commuter traffic (maybe cheat and use dummy traffic?) adding to morning and evening rush hours.

**Comment by dymanoid** [comment]
> I doubt it's possible, but it would be awesome if there was business commuter traffic (maybe cheat and use dummy traffic?) adding to morning and evening rush hours.

I don't think somebody will ever notice this, and if they do, then probably they will complain about that.

So this will be the feature for dummy traffic only. The tourists topic will be covered by #110.

**Comment by Sipke82** [comment]
During rush hour in my 140k city, the vehicle limit is hit, so I wouldn't really want more cars then.

**Comment by aubergine10** [comment]
Assuming that rush hour is the same in both cities, and they have long drive from the other city to your city, maybe the rush hour of outside connection traffic could occur 1-2 hours after the local rush hour?

**Comment by dymanoid** [comment]
I think that no one will notice these details. This is dummy traffic after all. So it will only change its intensity depending on daytime (day time = vanilla level, night time = less traffic). No additional rush hours due to dummy traffic!
