### ISSUE TITLE
What effect does NIMBY policy have on RT?

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#103]
> NIMBY policy: No loud noise in the night! Leisure specialized areas will close for the night. Reduces noise pollution caused by leisure. No loud noise in the night! Leisure specialized areas will close for the night. Reduces noise pollution caused by leisure.

My guess is the vanilla game just reduces income (by ratio of day vs. night hours on a weekly basis or something) and not much else.

With the policy active, could RT deactivate (or does it already) the leisure buildings?

What about things like amusement parks - are they just "park assets" or actual "commerce - leisure"?

And fireworks - #102 ?

**Comment by dymanoid** [comment]
Currently, the NIMBY policy in **Real Time** only gets involved when deciding which leisure building to visit. So the citizens just won't go to those at night.
It makes sense to switch their lights off (having now #73).
However, I'm not sure that deactivating a building completely is a good idea. It will lose its workers and goods causing only problems then.

Amusement parks are parks, not leisure, from game's point of view.

**Comment by aubergine10** [comment]
Relates to #128

**Comment by aubergine10** [comment]
IMO the amusement parks/areas should really be treated as leisure in respect to NIMBY policy (unless amusement park area has 'night tours' policy set). They're very noisy, all about leisure, and purpose of NIMBY is to keep the place quiet at night so residents can get good nights' sleep.

Also, should NIMBY policy trigger at "GoToSleepHour" setting rather than "at night" (I assume in vanilla that means "at sunset")?

**Comment by dymanoid** [comment]
NIMBY policy might be triggered in-game by the sunset (didn't really check what does this mean actually). But for **Real Time**, it is indeed the go-to-sleep time: citizens don't schedule parties at NIMBY-active buildings, and also citizens leave NIMBY-active buildings as soon as possible.

Regarding the amusement parks: while this is indeed realistic, it's somehow not a part of the game. There's no info about it, so most players just won't know that if we would implement it. So I doubt the effort is worth it.

Can we close this one or do you still have other questions?

**Comment by aubergine10** [comment]
Yes, can be closed  - thanks for the updates! This mod just keeps getting better :D
