### ISSUE TITLE
Use custom events from assets that provide Rush Hour event template

### ISSUE THREAD

**Issue by dymanoid** [dymanoid/RealTime#107]
There are some assets (buildings) from the Steam Workshop that provide XML-based custom event templates introduced in **Rush Hour**.
Since **Real Time** has similar custom events logic and even derive the events format from **Rush Hour** (exactly for the sake of being compatible), those event templates should be used in the game for creating events.

**Real Time** currently provides only basic events functionality (not affecting economy etc.), so those templates should only be used for attending events in particular buildings.

The advanced event functionality will be implemented in a separate mod in the future, and all event related logic will be moved there too.

**Comment by ToonHermans** [comment]
Do you know when we can expect that separate mod? Should we think about weeks or more like months?

**Comment by dymanoid** [comment]
There are no plans currently.

This issue only addresses loading of the Rush Hour event definitions from building assets that provide those events. However, the custom events are very simplified in **Real Time**. The loaded Rush Hour events will cause some events to take place in the corresponding Workshop buildings. The citizens will visit those events. However, there is no economy impact and no customization.
