### ISSUE TITLE
Since the dayplans of citizens, commercial buildings often complain about too few customers.

### ISSUE THREAD

**Issue by Sipke82** [dymanoid/RealTime#108]
Since the dayplans of citizens, commercial buildings often complain about too few customers.

**Comment by dymanoid** [comment]
Would you share a save game that illustrates this? Preferably with as few additional mods as possible.

**Comment by Sipke82** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1449572976
It's with a great collection of mods and assets (sorry), how can i quickly make a collection of that. Somehow i only get to a point where i have to select everything one by one.

**Comment by dymanoid** [comment]
Go to **Real Time**'s settings and decrease the local search probability to 20% or less. See if that helps with the "no customers" problem.

**Comment by Sipke82** [comment]
I've set the local search probability to 15%, but it did not help. still complaining and then abandonment. Before this update, the city worked fine, i dont think i have zoned too much..
![image](https://user-images.githubusercontent.com/30873812/43161944-d62445c6-8f89-11e8-97eb-5fe7a32d6bff.png)
 Also commercial demand is completely gone.

**Comment by bbatliner** [comment]
I got this issue starting with with Rush Hour 2 (not Rush Hour 1). Even the latest update of RH2 didn't fix it for me, after a few days in-game. I'm currently 1 day into Real Time and most of my commercial buildings are still reporting not enough customers. I have zero commercial demand in my city. Could be a real problem.

**Comment by dymanoid** [comment]
Alright, a new hotfix is out.
I modified the shopping behavior so that citizens will try to reach shops as soon as possible when they need to buy something. That doesn't mean that they will leave work or school for that, however.
Try it out and please report if things get better.
This is a quick fix before version 1.9 is released. There, the feature #86 will enable a more advanced shop selection algorithm which should completely solve the demand/commercial drop problems.

**Comment by aubergine10** [comment]
Commerce is still flatlining for me despite the hotfix.

**Comment by dymanoid** [comment]
Are we discussing the "no customers" or "no demand" here?

**Comment by aubergine10** [comment]
My exist commerce has customers and is doing fine, but the demand graph (three bars bottom of screen) has flatlined for commerce for a few game days now, despite increasing residential zoning. Industry demand is acting normally, increasing as residential increases.

**Comment by dymanoid** [comment]
The demand topic is addressed in #115.

**Comment by dymanoid** [comment]
Spotted an issue. Some citizen can "sleep at home" too long, thus they are not going shopping even they need to.

**Comment by dymanoid** [comment]
This is solved in the [Hotfix 1.8.5](https://github.com/dymanoid/RealTime/releases/tag/1.8.5)
