### ISSUE TITLE
Improve lights off behaviour

### ISSUE THREAD

**Issue by Sipke82** [dymanoid/RealTime#109]
Although i like the lights off feature some things come to mind:
I'm not sure how you implemented it, i saw some suggestion to turn buildings off and stuff like that..

Therefore i was wondering is it possible to turn a % of industrial buildings off at nigh, i see those industrial area's still very very busy at night. and i saw trucks delivering raw materials to buildings with lights off.

Also I think Large office buildings should be excluded from the lights off...

**Comment by dymanoid** [comment]
This is only a visual feature. When the lights are out, the building keeps working. Nothing prevents from visiting it, delivering goods, etc.

The time when and whether a building switches the lights off are exactly the same as for work shifts. Refer to the work shifts description on the Workshop page. Offices have no night shifts, so they switch the lights off.

**Comment by aubergine10** [comment]
I love the lights out feature - combined with everything else, night time is actually starting to feel more like night time.

Agree with Spike that office (and commercial) towers should probably stay lit for longer, as there seems to be a tradition of wasting as much power as possible in such buildings.

Some high-res zones look odd as some buildings are fully lit, others are fully un-lit. It's like someone went round randomly toggling the main power switch to the buildings. Is there anything that allows a percentage of the lights to be set - that would work better, visually, for large towers.

Also, completely unrelated to RT, check out the awesome window lighting (additive shader, so prolly overkill imo) on this recent workshop asset: https://steamcommunity.com/sharedfiles/filedetails/?id=1445037369&searchtext=

**Comment by dymanoid** [comment]
Unfortunately, we cannot control each "window" of a building independently. At least, without texture manipulation (this is what I'll never try to do).

So we either completely shut the building down, or it is fully lit.

Maybe don't affect offices and high commercial buildings at all? Let them be lit all night long?

**Comment by aubergine10** [comment]
IMO the residential towers should still be going dark - unlike office blocks, you don't generally see resi towers fully lit at night.

**Comment by aubergine10** [comment]
Actually, many places do turn the lights out on unique buildings. Eiffel Tower, for example, has lights on from sunset to 1am (2am for summer months). Statue of Liberty, on the other hand, never turns lights out (if there's a power cut causing them to go out it actually makes news headlines).

**Comment by Sipke82** [comment]
Limit the effect to low density buildings (residential, commercial and generic industries) seems the most logical approach to me.

**Comment by aubergine10** [comment]
What Spike says.

The real problem here is the way asset authors (including those at CO) approach the night lights for their assets (road maintenance building being a prime example). It's going to take a separate mod to sort out the assets themselves.

**Comment by dymanoid** [comment]
I'll change the behavior in this way, we'll see what the community means.

Lights go out for:

- _residential low_ **every night**
- _residential high level 1 and 2_ **every night**
- _industrial_ **when not working** (i.e. forestry and agriculture every night, generic on weekends)
- _offices level 1_ **every night**

**Comment by Sipke82** [comment]
Hmmm, well I guess this qualifies for an modoption setting?
