### ISSUE TITLE
Overnight and free morning shifts

### ISSUE THREAD

**Issue by dymanoid** [dymanoid/RealTime#11]
As reported on the Steam Workshop:

> Could it be possible to reserve 10 or 20% of the cims to work at dawn, as it happens in the real world? It would be very good to further enhance the reality that this mod proposes to bring.

Additionally, there might be overnight shift jobs available in the city.

**Comment by aubergine10** [comment]
How will the mod determine where the late/early/shift workers will apply?

Some incomplete random thoughts....

24/7 shift working (full complement of workers at all times):

* Warehouses - any industry building with "Warehouse" or "Cargo" in asset name
* Oil and ore industry
* Potentially any buildings in proximity to transport and cargo hubs

Small overnight presence (eg. security, cleaners, stock taking, etc):

* High density commercial

Early morning presence:

* Low density commercial

**Comment by dymanoid** [comment]
Implemented solution:

- Many service buildings (police, medical etc.) and low density, leisure, and tourist commercial buildings accept workers even on Weekends
- Many service buildings and all commercial buildings have three work shifts: morning-to-evening (first shift), evening-to-midnight (second shift), and midnight-to-morning (night shift)
- Low density commercial buildings have an extended first shift starting very early
- The work shift ratios are 50% first shift and 25% + 25% the others
- Industry and offices have an usual 5-day week with a single shift
