### ISSUE TITLE
Sudden daytime / nighttime switch

### ISSUE THREAD

**Issue by TMaekler** [dymanoid/RealTime#113]
I have an issue where at the point in time when day switches to night and night to day, that a sudden jump in time occurs. It seems to happen in conjunction with Ultimate Eyecandy, which is in sync beforehand, but after the jump has a very different time.

**Comment by dymanoid** [comment]
Ultimate Eyecandy is an incompatible mod.

**Comment by TMaekler** [comment]
Oh, didn't know. Can you add that information to the mod info on steam?

**Comment by dymanoid** [comment]
@TMaekler, if you read the mod info carefully then you can see that it's already there.
