### ISSUE TITLE
Some parks always render cims due to animations

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#116]
Some parks have special animations for cims.

Examples:

* Bouldering (PL DLC - nature reserve) - cims climbing the rocks
* Climbing frame (probably PL DLC?) - cims on see-saws
* Most fairground attractions (PL DLC - amusement park)
* Probably lots of others that I didn't notice

These animations are always active, 24/7, so long as the building is operating.

This could potentially be part of the issue of people seeing cims in parks after sleep time (#76).

If the building is turned off, or some other issue that "disables" it (eg. power cut, no water, etc), the animated cims are removed making the park look "closed".

**Comment by dymanoid** [comment]
Already thought about that. Would play nicely together with #85.

**Comment by aubergine10** [comment]
I notice also the affected parks (or whatever they are in terms of asset type) don't seem to turn lights off at night either.

**Comment by dymanoid** [comment]
They should. But only after midnight, because the second shift ends at midnight.

**Comment by aubergine10** [comment]
Ignore the stuff I said about lights staying on in those parks - it seems that during a moment of glory I'd manually plopped prop lights in my parks, so they weren't even part of the asset. Doh!

**Comment by dymanoid** [comment]
@aubergine10, this feature is implemented in such way that the bonfires in the parks also stop in the night (unless the 'Night tours' policy is activated).
