### ISSUE TITLE
Fire animation continues all night

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#117]
In ParkLife DLC, there's some assets in Nature Reserve parks menu that include a camp fire - I assume a special prop that emits particles & light.

Those fires burn all night. It would be nice (and safer for the cims lol) if there was a way to put them out around sleep time.

Assuming it's one specific prop (which I think might have existed in the vanilla game for some years?) it could potentially be handled city-wide somehow? It's primarily the light component of it that's the issue; the smoke wouldn't be that noticeable without the light effect.

I think there's some way to set start/stop times on light features, for example asset authors use this script to set on/off times: https://gist.github.com/ronyx69/bfa8940c8d68f99b8826c88af51a39b7

**Comment by dymanoid** [comment]
Is it worth to invest time in such a mini-thing?

**Comment by aubergine10** [comment]
Maybe not in main mod. I'm just getting in to modding so might try this as my first mod - if there's some way to alter the prop that's used (or whatever it is) I might be able to set the "off time" in a single location and have all the fires go out just after night budget kicks in.

..well, second mod - my first mod was utter disaster: trying to delete weird junk that often appears on maps at 0,0,0 (or whatever the center of map is) at very bottom, usually under terrain or water where nobody notices.

**Comment by aubergine10** [comment]
Is there a guide anywhere that explains how you implemented the config system in RealTime?

**Comment by aubergine10** [comment]
Done - is it OK if I close this issue?

My plan is to have a mod that provides control over bonfires both for vanilla and RT games:

* When fires are lit (specific time, or when day budget kicks in)
* When they go out (specific time, or when night budget kicks in)
* Maybe option to have fire lit only while cims are visiting the building
* Option for fire to go out when it rains

This stuff could feasibly go in realtime, but I'm keen to get in to modding.

**Comment by dymanoid** [comment]
If you want to implement this yourself and don't need this feature in **Real Time**, then of course you can close this. Otherwise, I mark the issue as **feature** and queue in the pipeline (indeed with very low priority).

**Comment by aubergine10** [comment]
Succeeding, slowly :) Learning C# is taking a little longer than expected (especially as I'm putting some generic code in to separate projects for reuse in future mods - overkill for current project, but I need to learn C# so...)

I'll close this for now and re-open if I fail to create my mod.

**Comment by dymanoid** [comment]
This feature is automatically implemented by #116.
