### ISSUE TITLE
Sunrise/sunset time tool tip

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#120]
Is there a way to indicate wake and sleep times in the yellow time bar (where events get marked)? Maybe a feint dotted or dashed line? Or different bar colour at night?

**Comment by dymanoid** [comment]
This is indeed possible, but why?

**Comment by dymanoid** [comment]
Okay, and for what? Sunset and sunrise is a plain visual thing with **Real Time**.

**Comment by aubergine10** [comment]
Just so I can glance at the bar and get a rough idea of how long until sunrise or sunset. While it's a visual thing when it occurs, there's nothing really giving indication in advance of when it will occur, especially when playing on different maps.

**Comment by Sipke82** [comment]
tbh, it feels for me like a bit too much. i mean you can just see if the sun is up or down?
If such a thing would get implemented i think it would make more sense to show wake up time and sleep time, as there is no other visual feedback on that. and those times actually impact the gameplay a bit, for instance at sleep time, citizens will goto bed etc.

**Comment by aubergine10** [comment]
It's just a "nice to have" (ie. bells and whistles), so not that important. I just get curious about the time in advance, and by time sunset/sunrise happen I'm usually distracted on something else [like freaking highway junctions](https://steamcommunity.com/sharedfiles/filedetails/?id=1453219797).

**Comment by dymanoid** [comment]
Sure, but this is also like in real life: a city mayor can be ~~enjoying a warm bath with some spicy señoritas~~ planning how to improve the citizens well-being while the city is totally clogged in a congestion.

**Comment by dymanoid** [comment]
Decided to not implement this. The sunrise and sunset times can be approximately determined using the zoom button where the sun and the moon symbols rotate around the globe. There is no real benefit in knowing those times precisely.
