### ISSUE TITLE
Time scaling / skipping

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#122]
As discussed in a few other tickets, most notably #118, the real life time taken to complete 1 game year is obviously quite long even with moderate speed slider settings.

> @Spike82 said: Well atm 1 realtime minute takes about 10 real life seconds for me. So a full year will cost me 1474 real life game hours., so if i play everyday 2 hours, it will take me 728 days to complete one game year.

Read the full suggestion from Spike82 [here](https://github.com/dymanoid/RealTime/issues/118#issuecomment-407900939) - what's written below is based on his suggestion.

As different gamers will want different time scales, I suggest a slider...

> What does 1 game week represent?

Steps on the slider:

* 7 days (~24 real life months per game year)
* 1 month (~7 real life months per game year)
* 1 season (~3 real life months per game year)

Season = 3 months a.k.a. "a quarter" of a year.

The RL estimates obviously depend on the time user spends playing game, and other factors like speed sliders and city size, so I "vagueified" it to clarify the gist.

Defaults to 7 days so new users get the full RealTime™ experience, and can change scale later if it's too slow for them.

**Comment by aubergine10** [comment]
The benefit of Spike's approach of skipping weeks or months, rather than days out of the week, is that it ensures players still see a whole week (Mon-Sun); it's still realtime, but, if you want the years to roll by quicker, you can choose to skip 3 weeks each month or 2 months each season.

**Comment by dymanoid** [comment]
After a deep investigation it seems that the feature discussed here is actually not possible.
The main reason for that is the fact that the game cannot cope with not-continuous time. E.g. the city statistics will be broken, disasters won't function properly.

I think I will not implement this one. Of course, #118 will be much less enjoyable because of that.

**Comment by Sipke82** [comment]
That's a real pity, doesn't RealTime use its own timescale? Uncoupled from the simulation time?

**Comment by dymanoid** [comment]
There is no possibility to "uncouple" the time flow from the simulation time. These are the same, just with different multipliers.
