### ISSUE TITLE
Students go to school, arrive too early and go home then

### ISSUE THREAD

**Issue by Gordon-Dry** [dymanoid/RealTime#130]
Especially when the time speed is set to a low value like 1 the students leave home, go to school (using public transport) and when they arrive it's still early, so they decide to go home again - but this time they do on feet... at least it looks like that because they don't go to the next bus stop, they go to a neighborhood which is opposing the direction where they came from.

**Comment by dymanoid** [comment]
Students cannot leave school even when they are too early at school.
I think you observe a "normal" vanilla behavior: when a student gets promoted to the next level (e.g. primary school to high school), he/she immediately leaves the building regardless of the school time. This can be mostly overridden by #82.
Regarding choosing how to travel: **Real Time** has no effect on _how_ citizens travel (on feet, by car, by public transport). This is done either by the game or by other mods. **Real Time** only tells citizens _when_ to leave, but not _how_ to get to target.

**Comment by dymanoid** [comment]
@nosh59, thanks for the overview. I already knew that. Actually, it is a part of #82 (the issue title is not that self-explanatory though).

@Gordon-Dry, does **Citizen Lifecycle Rebalance** help? If yes, we could close this issue.

**Comment by Gordon-Dry** [comment]
It seems so, but I have to investigate further ...

**Comment by dymanoid** [comment]
@Gordon-Dry, having #82 implemented and released with 1.10, you should no longer see any students leaving school at random times. Even when they graduate, they continue studying on their last day and leave school together with all other students.

Please confirm.
