### ISSUE TITLE
"No locale found"

### ISSUE THREAD

**Issue by jamson1993** [dymanoid/RealTime#131]
No locale found was shown in game (in mod option).
Mod functioning properly in saved game.
![no locale found](https://user-images.githubusercontent.com/41909319/43401254-41c1664e-9442-11e8-88df-40b44112d139.jpg)

**Comment by dymanoid** [comment]
Please provide the game log file.

**Comment by bennett62** [comment]
Same problem as Jamson
https://gist.github.com/bennett62/321d265e5b17218e1120a094c7d46c7e

**Comment by jamson1993** [comment]
[output_log.txt](https://github.com/dymanoid/RealTime/files/2241561/output_log.txt)
Log file here. Thanks.

**Comment by dymanoid** [comment]
Okay guys, I see that you're running your games without Steam. This is not supported by **Real Time**, sorry.

**Comment by bennett62** [comment]
Oh, okay. So, I have tried to find some screenshots of the menu everywhere but I couldn't. There is somewhere I can find?

**Comment by dymanoid** [comment]
The only official place you can get **Real Time** is the Steam Workshop. If you obtained the mod from somewhere else, I cannot support you. Don't get me wrong. I have no idea who and how built the binaries and packaged the content. So that's it.

**Comment by bennett62** [comment]
Oh, no problem then. Thank you for the attention and congrats for the mod!
