### ISSUE TITLE
Level color-coding broken on residential buildings

### ISSUE THREAD

**Issue by drewzarn** [dymanoid/RealTime#134]
**Describe the bug**
With Real Time enabled, residential buildings don't show color coding in various info views. Levels, population, education are all affected. The screenshots below show the education info view, with and without RT enabled

**Additional mods**
Skylines Overwatch
Enhanced Hearse AI
25 Spaces
Automatic bulldoze v2
Automatic Emptying
Better Bulldoze tool
Clouds & Fog Toggler
Daylight Classic
Elevated Stops Enabler
Enhanced Zoom Continued
Fine Road Tool
Loading Screen Mod
Move It
Parallel Road Tool
Precision Engineering
Quay Anarchy
Traffic Manager: PE
Unlimited Money
Unlimited Soil

**Game log file**
[output_log.txt](https://github.com/dymanoid/RealTime/files/2247789/output_log.txt)

**Screenshots** (optional)
![with](https://user-images.githubusercontent.com/18582889/43497668-8eab8ff2-9500-11e8-96f1-5c8eeb7b8bc2.png)
![without](https://user-images.githubusercontent.com/18582889/43497700-b4688f1a-9500-11e8-910e-a019078202c4.png)

**Comment by benzoll37** [comment]
I think it happens at night, the lights buildings are OFF. Maybe it's normal for it.

**Comment by dymanoid** [comment]
Yes, this is by design. In the "sleep time", the resident buildings do not show their stats.
While this might be good for education (no school at night), it's not appropriate for building levels. This should be changed - the building level stats as well as population stats should be visible at night too.

**Comment by Sipke82** [comment]
I think that even for education, you should still be able to see the stats at night.
