### ISSUE TITLE
What happens when you don't use dynamics?

### ISSUE THREAD

**Issue by XDrinkingSugarX** [dymanoid/RealTime#136]
What I mean is, is that what happens when you turn off dynamic weather and dynamic day/night cycle. Does anything happen? I don't know if this issue is in question format but anyway. I can't use this mod right now and I can't experiment myself. Thanks

**Comment by dymanoid** [comment]
The weather doesn't affect **Real Time** at all. So you can set this option as you wish. However, the game will do something with that. Or maybe some other mods do respect this option.

If you disable the _day/night cycle_ option, the sun will be always at its highest point (noon). However, the time will run as usual, so citizens will go to sleep etc. Please note that I'm not testing the mod with this option disabled, so there might be some unexpected glitches.
