### ISSUE TITLE
Events stop being scheduled after a few days

### ISSUE THREAD

**Issue by Sehender1** [dymanoid/RealTime#144]
**Describe the bug**
If I place a building that has events (art museum, aquarium, etc.) it seems to have a few events for the fits few days, but then they stop being scheduled. 
**Additional mods**
List the most important mods you are using, especially those that might conflict with **Real Time**.
If not sure, list all of them.
using network extensions, 81 tiles, unlimited trees, multi-track station enabler.. 
nothing time-related, though. 

**Game log file**
If the bug reason is not obvious, please provide the game's log file. You can [read here](https://steamcommunity.com/sharedfiles/filedetails/?id=463645931) how to do this.

**Screenshots** (optional)

**Comment by Sehender1** [comment]
Actually, nm. 
resolved over time on its own..

**Comment by dymanoid** [comment]
Events don't necessarily take place every day. There can be up to 48h without any events.
