### ISSUE TITLE
Reference unit "40 min"

### ISSUE THREAD

**Issue by benzoll37** [dymanoid/RealTime#147]
Hello, I have seen as all references of tourists by parks, passengers, production of water pumps, etc etc have passed to "40 min".
It's real, but it's a strange reading to see.
"40 min" is really a full day of 24h? If so, maybe "/ day" would be more natural.
I just did a full translation to Spanish, and it looks weird "last 40 min", I looked in the xml but I did not see where to change once **{unit}**, and that it would be valid for all {unit}.
Then I am manually changing and it works ok.

Postscript.- I've been all afternoon for it, and it's a simple translation. Incredible the merit that you have the modders, I take off my hat.

**Comment by dymanoid** [comment]
These are not hard-coded **40 min.**. These units change when you change the time speed. These can be **20 min.**, **10 min.** and so on. For details, read my last comment in #59.

**Comment by benzoll37** [comment]
Ok, sorry. I did not know it.

**Comment by dymanoid** [comment]
No problem. I need to create a "How to play" guide where these things are explained, just can't find no time for that. **Real Time** becomes more complex each day, and it's not always obvious what's happening.
