### ISSUE TITLE
adjustable transport dispatch number by time

### ISSUE THREAD

**Issue by ryanhsin0508** [dymanoid/RealTime#150]
there are few passengers in night, can this mod involve public transport? just make it like Cities in motion, you can control dispatch number eg. 6:00 - 21:00 30 buses / 21:00 - 6:00 10 buses

**Comment by dymanoid** [comment]
Same as #126.

Public transport is out of scope for **Real Time**. Use other mods (like **Transport Line Manager**) or vanilla budgets & line settings "day/night", as suggested by @benzoll37.
