### ISSUE TITLE
`WorkshopId` should be `ulong` not `long`?

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#153]
[In RealTimeMod.cs](https://github.com/dymanoid/RealTime/blob/master/src/RealTime/Core/RealTimeMod.cs#L21):

```private const long WorkshopId = 1420955187;```

But later in the file:

```
        private static string GetModPath()
        {
            PluginManager.PluginInfo pluginInfo = PluginManager.instance.GetPluginsInfo()
                .FirstOrDefault(pi => pi.publishedFileID.AsUInt64 == WorkshopId);

            return pluginInfo?.modPath;
        }
```

You're comparing to `pi.publishedFileID.AsUInt64` - so shouldn't `WorkshopId` be a `ulong`?

**Comment by dymanoid** [comment]
For commenting the code, please use direct "code comment" feature, not "issues". You can open the source code in the GitHub web view and add your comments directly to the corresponding code lines.

Please move your question there and close the issue.

**Comment by aubergine10** [comment]
What's the specific procedure? I don't see a direct option to comment, but if I select the line of code I see option to create new issue relating to that line (although on doing so I didn't see any clear indication the issue would be linked to the code)? Or should I track down the commit that added that line and comment there?

**Comment by dymanoid** [comment]
Yeah, that's not so straight forward. The comments are available for commits only, not for the plain code view. 

- Open the file in the GitHub source view.
- Pick the line of interest and choose "View git blame".
- On the left, pick a commit that changes the line of interest an click on that.
- In the commit, find the line an hover the mouse cursor over it - a blue plus symbol appears. That's the "add comment" button.
