### ISSUE TITLE
Travel to outside connections for citizens

### ISSUE THREAD

**Issue by Sipke82** [dymanoid/RealTime#158]
Could you allow citizens to travel to the outside connections? for example business trips and holidays. Preferably using all means of transport
- Planes
- PT
- Cars
- Cruiseships

Especially for the trainstations, airport and harbors, i've always found it highly unrealistic that almost no people are leaving, resulting in near empty trains/ships/planes. It would be nice to see those parking lots near airports/harbors/trainstations getting filled with cims going for trip.

**Comment by dymanoid** [comment]
Decided to treat this one as a new mod request. The idea is great, it would be better to also enable it for those players who don't use (like) **Real Time**.
