### ISSUE TITLE
Real Time : Can run only steamworkshop

### ISSUE THREAD

**Issue by bammcool2011** [dymanoid/RealTime#159]
**Hello @dymanoid!**
I've some problem about RealTime mod, I think it from download without using steamworkshop.

**Can you fix it?**, Because my steamworkshop didn't download when I subscribed every mod :<
Your mod is so great, I love it! 

*I using [Skymods ](http://smods.ru/)to download mod from Steamworkshop

**Comment by dymanoid** [comment]
**Real Time** only works when subscribed to in Steam Workshop. If your Workshop can't download mods for some reason, then please contact the Steam support to resolve your issue.
