### ISSUE TITLE
Office workhours are till 12:00 PM while they should end at 6pm

### ISSUE THREAD

**Issue by Sipke82** [dymanoid/RealTime#160]
A lot of users have reported busy midnights, perhaps this bug is due: Office workers work till 12:00 PM instead of 6 PM:
![image](https://user-images.githubusercontent.com/30873812/44484079-09afaa00-a64d-11e8-99d0-4779563ed092.png)

**Comment by dymanoid** [comment]
12 p.m. is noon - lunch time.

**Comment by Sipke82** [comment]
I feel silly now  (im a 24h clock user :-)
well according to that page there are different conventions....
Nevertheless, i'm not entirely sure about the midnight traffic... so close for now? or let's add 24h clock ?

**Comment by Sipke82** [comment]
Thank for your reply, that explains the 12h clock... would be cool to have the 24H version and English. I hate to say this, as this mod is way superior, but the old rush hour mod had an 24H clock mod option.

**Comment by dymanoid** [comment]
See #162 for that.
