### ISSUE TITLE
How to get angry CIMS?

### ISSUE THREAD

**Issue by Sipke82** [dymanoid/RealTime#161]
Lot of workers were waiting all day for a parking spot, still not angry:
![image](https://user-images.githubusercontent.com/30873812/44485388-b17aa700-a650-11e8-9ca6-5616339fccae.png)

**Comment by dymanoid** [comment]
I guess "waiting for a parking lot" is some special state where TM:PE blocks **Real Time**. Normally, a citizen should cancel the journey if it's longer than 2-3 hours.

**Comment by Sipke82** [comment]
Now, during the evening rush hour, cims are wainting in traffic to get home:
![image](https://user-images.githubusercontent.com/30873812/44619640-87142e00-a88a-11e8-85e8-3db2ffb4fda4.png)
Still, no one angry:
![image](https://user-images.githubusercontent.com/30873812/44619647-985d3a80-a88a-11e8-82e4-a081b2a656c6.png)

**Comment by dymanoid** [comment]
But it's only 6 p.m. The stuck citizens should start complaining when they are still stuck at 9 p.m.

But I see not a single dark blue building on your screenshots. Do you have public transport? It seems that some mod prevents **Real Time** from collecting that information.

**Comment by Sipke82** [comment]
I have set work end time at 4:45. Because i wanted to see the traffic jams earlier in the evening.
I do have PT, depending on time of day 3k - 4k passengers per 10 mins

**Comment by dymanoid** [comment]
Okay, so the only explanation I have is that some other mod blocks **Real Time** from getting those citizens complaints. You could try disabling some of them (that might affect citizens moving or behavior) and see if that helps.

**Comment by Sipke82** [comment]
Hmm, went through my list of mods:
![image](https://user-images.githubusercontent.com/30873812/44621349-19293000-a8a5-11e8-9584-3c5c809c4c1c.png)
![image](https://user-images.githubusercontent.com/30873812/44621352-280fe280-a8a5-11e8-9b99-59b4be86ad60.png)


Still all my buildings are blue.. Perhaps my transportation infrastructure is perfect :P

To even challenge it even more, I've created 5000 jobs on top of a mountain, with only 1 small road going there and a cable car, still blue:
![image](https://user-images.githubusercontent.com/30873812/44621328-c9e2ff80-a8a4-11e8-8796-c8916fe6d592.png)

**Comment by dymanoid** [comment]
Disable all other mods and see if that helps. Again, something prevents **Real Time** from collecting the data.

**Comment by Sipke82** [comment]
When i disable TMPE, the feature is working! So seems to be incompatibility with TMPE on my system at least.

Interestingly, in both TMPE and Realtime, I've enabled popups to inform me about conflicting mods. However i see no popups.

**Comment by dymanoid** [comment]
That's very strange, because I tested this feature with TM:PE and it was working.
Can you tell what TM:PE config are you using? (Which features are active?)

**Comment by Sipke82** [comment]
![image](https://user-images.githubusercontent.com/30873812/44621936-99ed2980-a8af-11e8-9405-90a5b616a58f.png)
![image](https://user-images.githubusercontent.com/30873812/44621940-aa9d9f80-a8af-11e8-9c1a-0354a88ce43b.png)
![image](https://user-images.githubusercontent.com/30873812/44621941-aec9bd00-a8af-11e8-8f38-3b016f69f97b.png)
![image](https://user-images.githubusercontent.com/30873812/44621943-b38e7100-a8af-11e8-987b-08276129262a.png)
![image](https://user-images.githubusercontent.com/30873812/44621944-b8ebbb80-a8af-11e8-9bc8-6cee7c59d28d.png)

And the, I think default, XML:
```
<?xml version="1.0" encoding="utf-8"?>
<GlobalConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.viathinksoft.de/tmpe">
  <Version>16</Version>
  <AdvancedVehicleAI>
    <LaneRandomizationJunctionSel>3</LaneRandomizationJunctionSel>
    <LaneRandomizationCostFactor>1</LaneRandomizationCostFactor>
    <LaneChangingBaseMinCost>1.1</LaneChangingBaseMinCost>
    <LaneChangingBaseMaxCost>1.5</LaneChangingBaseMaxCost>
    <LaneChangingJunctionBaseCost>2</LaneChangingJunctionBaseCost>
    <JunctionBaseCost>0.1</JunctionBaseCost>
    <MoreThanOneLaneChangingCostFactor>2</MoreThanOneLaneChangingCostFactor>
    <TrafficCostFactor>4</TrafficCostFactor>
    <LaneDensityRandInterval>20</LaneDensityRandInterval>
    <MaxTrafficBuffer>10</MaxTrafficBuffer>
  </AdvancedVehicleAI>
  <DynamicLaneSelection>
    <MaxReservedSpace>0.5</MaxReservedSpace>
    <MaxRecklessReservedSpace>10</MaxRecklessReservedSpace>
    <LaneSpeedRandInterval>5</LaneSpeedRandInterval>
    <MaxOptLaneChanges>2</MaxOptLaneChanges>
    <MaxUnsafeSpeedDiff>0.4</MaxUnsafeSpeedDiff>
    <MinSafeSpeedImprovement>25</MinSafeSpeedImprovement>
    <MinSafeTrafficImprovement>20</MinSafeTrafficImprovement>
    <VolumeMeasurementRelSpeedThreshold>50</VolumeMeasurementRelSpeedThreshold>
  </DynamicLaneSelection>
  <Main>
    <MainMenuButtonX>459</MainMenuButtonX>
    <MainMenuButtonY>25</MainMenuButtonY>
    <MainMenuButtonPosLocked>false</MainMenuButtonPosLocked>
    <MainMenuX>185</MainMenuX>
    <MainMenuY>68</MainMenuY>
    <MainMenuPosLocked>false</MainMenuPosLocked>
    <DisplayedTutorialMessages>
      <string>MainMenu</string>
      <string>ToggleTrafficLightsTool</string>
      <string>LaneConnectorTool</string>
      <string>PrioritySignsTool</string>
      <string>ParkingRestrictionsTool</string>
      <string>SpeedLimitsTool</string>
      <string>JunctionRestrictionsTool</string>
      <string>VehicleRestrictionsTool</string>
      <string>TimedTrafficLightsTool</string>
      <string>TimedTrafficLightsTool_AddStep</string>
      <string>TimedTrafficLightsTool_Copy</string>
      <string>SpeedLimitsTool_Defaults</string>
      <string>TimedTrafficLightsTool_AddJunction</string>
    </DisplayedTutorialMessages>
    <EnableTutorial>true</EnableTutorial>
    <TinyMainMenu>false</TinyMainMenu>
    <GuiTransparency>30</GuiTransparency>
    <OverlayTransparency>40</OverlayTransparency>
    <ShowCompatibilityCheckErrorMessage>true</ShowCompatibilityCheckErrorMessage>
  </Main>
  <ParkingAI>
    <ParkingSpacePositionRand>32</ParkingSpacePositionRand>
    <VicinityParkingSpaceSelectionRand>4</VicinityParkingSpaceSelectionRand>
    <MaxParkingAttempts>10</MaxParkingAttempts>
    <MaxParkedCarInstanceSwitchSqrDistance>6</MaxParkedCarInstanceSwitchSqrDistance>
    <MaxBuildingToPedestrianLaneDistance>96</MaxBuildingToPedestrianLaneDistance>
    <MaxParkedCarDistanceToHome>256</MaxParkedCarDistanceToHome>
    <MaxParkedCarDistanceToBuilding>512</MaxParkedCarDistanceToBuilding>
    <PublicTransportDemandIncrement>10</PublicTransportDemandIncrement>
    <PublicTransportDemandWaitingIncrement>3</PublicTransportDemandWaitingIncrement>
    <PublicTransportDemandDecrement>1</PublicTransportDemandDecrement>
    <PublicTransportDemandUsageDecrement>7</PublicTransportDemandUsageDecrement>
    <ParkingSpaceDemandDecrement>1</ParkingSpaceDemandDecrement>
    <MinSpawnedCarParkingSpaceDemandDelta>-5</MinSpawnedCarParkingSpaceDemandDelta>
    <MaxSpawnedCarParkingSpaceDemandDelta>3</MaxSpawnedCarParkingSpaceDemandDelta>
    <MinFoundParkPosParkingSpaceDemandDelta>-5</MinFoundParkPosParkingSpaceDemandDelta>
    <MaxFoundParkPosParkingSpaceDemandDelta>3</MaxFoundParkPosParkingSpaceDemandDelta>
    <FailedParkingSpaceDemandIncrement>5</FailedParkingSpaceDemandIncrement>
    <FailedSpawnParkingSpaceDemandIncrement>10</FailedSpawnParkingSpaceDemandIncrement>
  </ParkingAI>
  <PathFinding>
    <PublicTransportLanePenalty>10</PublicTransportLanePenalty>
    <PublicTransportLaneReward>0.1</PublicTransportLaneReward>
    <HeavyVehicleMaxInnerLanePenalty>0.5</HeavyVehicleMaxInnerLanePenalty>
    <HeavyVehicleInnerLanePenaltySegmentSel>3</HeavyVehicleInnerLanePenaltySegmentSel>
    <IncompatibleLaneDistance>2</IncompatibleLaneDistance>
    <UturnLaneDistance>2</UturnLaneDistance>
    <MaxWalkingDistance>2500</MaxWalkingDistance>
    <PublicTransportTransitionMinPenalty>0</PublicTransportTransitionMinPenalty>
    <PublicTransportTransitionMaxPenalty>100</PublicTransportTransitionMaxPenalty>
  </PathFinding>
  <PriorityRules>
    <MaxPriorityCheckSqrDist>225</MaxPriorityCheckSqrDist>
    <MaxPriorityApproachTime>15</MaxPriorityApproachTime>
    <MaxPriorityWaitTime>100</MaxPriorityWaitTime>
  </PriorityRules>
  <TimedTrafficLights>
    <FlowWaitCalcMode>Mean</FlowWaitCalcMode>
    <FlowToWaitRatio>0.8</FlowToWaitRatio>
    <SmoothingFactor>0.1</SmoothingFactor>
  </TimedTrafficLights>
</GlobalConfig>

```
