### ISSUE TITLE
Time format according to operating system locale

### ISSUE THREAD

**Issue by dymanoid** [dymanoid/RealTime#162]
If the game language is English, an English US locale is automatically applied. This forces e.g. a 12h time format.

It would be great if the operating system could tell the current locale. So, when choosing English as game language, the OS locale should be considered (allowing a 24h time format with English language).

**Comment by dymanoid** [comment]
Investigation shows that the Unity engine has a bug that makes it impossible to get the operating system locale. It might be worked around with a native plugin for each platform (Windows, Mac, Linux), but it seems to me that it's too much overhead for such a little feature.

I will think about alternatives.

**Comment by DaEgi01** [comment]
Why not just have a 12h/24h clock dropdown?

**Comment by dymanoid** [comment]
It's not just about 12h/24h, but e.g. also about DD/MM/YYYY vs. MM/DD/YYYY etc.

**Comment by DaEgi01** [comment]
another dropdown ;P

**Comment by dymanoid** [comment]
To minimize the efforts for this feature, a new option is introduced in the mod's settings. It switches the date and time formats to English-US. By default, English-GB is now used.
