### ISSUE TITLE
Improve lights off part 2

### ISSUE THREAD

**Issue by Sipke82** [dymanoid/RealTime#163]
see also discussion in #109 

I still think high res residential should stay lit during light, look at the dark pit:
![image](https://user-images.githubusercontent.com/30873812/44489953-3e2b6200-a65d-11e8-98d2-0c0c3cd23151.png)

In addition i think that IT offices should also stay lit (they are level 1)
Perhaps better would be to make it depend on building height?

**Comment by aubergine10** [comment]
It just means half your city is in North Korea :p 

The problem I have with lit towers at night is their light design is usually really, really bad. It looks like the occupants have filled their rooms with dozens of flood lights and thrown away their curtains in a bid to achieve maximal light pollution.

If there was some way to make residential towers have dimmer, less-white lights, and ideally textures like that tower in OP, it would be fine. But the way things are with most towers, they look very terrible at night. See also: The road maintenance building at night - urgh!

**Comment by Sipke82** [comment]
Still most of my cities are not "North Korea" style... Perhaps make it an option if no consensus can be reached?

**Comment by dymanoid** [comment]
I will implement an option like "maximum building level that switches the lights off at night" for residential, commercial, and office buildings. Defaults will be level 1 (as it's currently implemented for commercial buildings and offices).

**Comment by aubergine10** [comment]
Great idea!

**Comment by Sipke82** [comment]
Although that would be an improvement. Shouldnt light off or on be determined by their height?

I think that even level 5 low denisity residential, should turn off their lights at night.
but level 1 high densitiy residential should should NOT turn off their lights at night.

Also IT offices are all level 1...

Perhaps the distinction can be made on the number of households/workers? or the "height" of a building.

**Comment by dymanoid** [comment]
I decided to implement this depending on the building height, as @Sipke82 suggested.
There will be a height threshold in the options. All buildings higher than that value will keep the lights on at night. Setting that value to 0 will cause all (inactive/not working/not visited) buildings to switch off the lights. So I hope everyone will find a useful value depending on their personal preferences.
