### ISSUE TITLE
Day reports

### ISSUE THREAD

**Issue by Sipke82** [dymanoid/RealTime#164]
As the actual game stats are now a bit un statisfying. Perhaps its a good idea to be able to show some kind of "day-report"or even "week report" as a pop-up. This popup could then show all kinds of stats, like how many people used PT, the amount of tourists which entered the city, did that amusement park really make a profit over the whole day? 
Perhaps it could even include some graph's?
Well we could brainstorm about the full contents of such reports but first we should know if it's even possible?

**Comment by dymanoid** [comment]
Why are current game stats unsatisfying? Why "50.000 citizens per day" is better than "500 citizen last 40 min."?

**Comment by DaEgi01** [comment]
no idea, maybe someone who knows enough about psychology can enlighten us. but that is something that bothered me for a long time too. somehow the old monthly reports in sim city were a lot more satisfying than a number that is constantly updated.
maybe its because some numbers are more interesting in accumulated form. like how many cims moved to or left the city during the last month compared to the previous month. it gives you a better overview of what is actually happening instead of having a number that constantly changes and that you forget about so long as its green. because it can be 500 citizen last 40 min, but still -1000 citizen last day. 
depends a lot on the information though. normally i prefer fast feedback loops, but in that case i believe that i would actually prefer a slower loop. could be just the age though ;D

it should be a separate mod imo though.

**Comment by Sipke82** [comment]
For example, it would be really cool to see something like this:
![image](https://user-images.githubusercontent.com/30873812/44603762-0ef32d00-a7e4-11e8-94ca-fbaff6994cb8.png)

Even if this is not possible an accumulated count gives more usefull information about the actual usage of the PT(in this example) because otherwise you are just getting a snapshot at one point, instead of the total picture.

Same holds true for example amusement parks, in the night they make no money. at day they make more money. But i would like to know, is my amusement park profitable? ...... You can only know that if you can use accumulated data.. all the expenses of the whole day and all the income of the whole day.

**Comment by dymanoid** [comment]
I agree with @DaEgi01 that this is actually out of scope for **Real Time**. The idea maybe makes sense, but it's not necessarily tied with **Real Time**. Better statistics might help building better cities, regardless of whether **Real Time** is used or not.

**Comment by Sipke82** [comment]
The reason why I thought of RealTime, is because now different things happen at different times. While in vanilla every part of the day is the same, in that case accumulated data doesn't add much.

**Comment by originalfoo** [comment]
There's a few stats mods I've been using that might be of interest (and maybe good place to incorporate ideas of this thread?):

* [Stats](https://steamcommunity.com/sharedfiles/filedetails/?id=1410077595&searchtext=stats) - shows icons for all kinds of stats, highly configurable
* [Watch It](https://steamcommunity.com/sharedfiles/filedetails/?id=1643902284&searchtext=watch+it) - like trimmed down version of Stats, but also allows in-game display of city statistics graphs etc
* [Show It](https://steamcommunity.com/sharedfiles/filedetails/?id=1556715327) - provides lots of charts on RICO buildings (inspired by Extended Building Information mod, but much better implementation)

**Comment by Sipke82** [comment]
I Still believe this is kind of a "RealTime"thing. as days are really a thing here. without "RealTime"all the graphs would just be flat....
Without realtime such graphs wouldn't make sense, so perhaps the new mod should be called: stats for realtime or something

**Comment by dymanoid** [comment]
Why? The player could select the stats period (day, week, month, year), so why this must be coupled with **Real Time**? In the vanilla game, the day stats will just change very quickly. In **Real Time** - slowly.

**Comment by Sipke82** [comment]
(the below scenario is if you just run the simulation, and not build anything)

In the vanilla game, every moment is almost the same..... so almost everything is just the same the whole time. so a number is just fine.

While in RT, we got a morning rush hour, normal activity during the day, evening rush hour, people go out clubbing and finally peace at night.
All these things make for instance the traffic busy at one moment, but not busy on another moment.  same for all kinds of other things. Therefore, graphs add something if you play with RT, but add almost nothing when playing vanilla, because it would mostly just be flat lines.
