### ISSUE TITLE
Next footbal match is in the past

### ISSUE THREAD

**Issue by Sipke82** [dymanoid/RealTime#166]
My next footbal match is in the past, see screen shot:
![image](https://user-images.githubusercontent.com/30873812/44619962-7e712700-a88d-11e8-9ab6-1e59157fe3e7.png)

**Comment by dymanoid** [comment]
No, it isn't. This is because of the game's weird time format.
**Real Time** shows you the date in the MM/DD/YYYY format (en-US).
The match UI shows you the date in the DD/MM/YYYY format (hard coded in the game somehow).
So it's the 5th of June when the next match will take place.

**Comment by dymanoid** [comment]
I agree, this is confusing. See #162 - when that's implementing, thing will get better.
