### ISSUE TITLE
Footbal stadium next match date got shifted ahead many months

### ISSUE THREAD

**Issue by Sipke82** [dymanoid/RealTime#168]
in my previous report regarding the footbal stadium, #166 , the next match will be at 5 june. after reload the game a few times, now its:
26 september:
![image](https://user-images.githubusercontent.com/30873812/44626698-33085880-a921-11e8-8026-ef5d4b20b228.png)
When i rebuild my football stadium, it acts normally again.
Perhaps related:  my Chirpy Launch site progression got reset, and is no progress is being made, until i rebuild it.

**Comment by dymanoid** [comment]
Which time speeds are you using in **Real Time**?

**Comment by Sipke82** [comment]
Using day speed 4 and night speed 6.
However, im not sure if it's related, but i did experiment with day speed 3 and night speed 5. but i changed it back to 4/6 because i didn't liked it.
