### ISSUE TITLE
Enhancement Request: Increase variation of work start+end hours

### ISSUE THREAD

**Issue by willbattel** [dymanoid/RealTime#178]
From what I've seen so far, almost all cims (excluding those in "overtime") leave for/from work at nearly the same time. It would be more realistic, and also more manageable from a city-building perspective, if there were much more variation to the start/end hours.

For example, if I set the work end hour to 6pm, then cims should start leaving around 4 and all will have left by 8, with roughly 50% having left by 6.

Rush hour should be dragged out longer than it currently is.

**Comment by dymanoid** [comment]
You can decrease the "on-time ratio" setting to e.g. 20%. Thus, 80% of the citizens will do overtime and will leave from work later.

Anyway, the current implementation is realistic enough. Citizens take into account the time they need to get to work, so they leave for work not at the same time. When leaving from work, some of the citizens return straight back home while the others go shopping or find entertainment. 
The main feature of **Real Time** is making the city realistic. I don't think that smoothing the rush hours is realistic - in the real world most workers tend to have fixed working hours.

I don't think it's necessary to change anything.

**Comment by Sipke82** [comment]
Ineend dymanoid, when going to work its fine.
But i do think that leaving from work could benefit from a bit more variation.
But this isn't a biggie... it's not too bad now.

**Comment by willbattel** [comment]
> I don't think that smoothing the rush hours is realistic - in the real world most workers tend to have fixed working hours.

Each civ has fixed working hours, but the working hours vary significantly between civs. Not all workplaces open at X and close at Y. The overtime mechanic definitely does help, but I'm still finding that 90%+ of my civs are starting work at the same time, and that is not realistic. I wouldn't say this is a huge deal if it weren't exaggerating the effects of rush hour, but that fact that 90% of my employed civs are on the road at a time is a problem no road network can reasonably handle. Perhaps you don't agree, and that's fine- this is your project not mine, but I believe that rush hour should be more spread out, so that closer to 60% of employed civs are on the road at most. The place I work at now opens (normal, non-overtime hours) at 7am, where the place I worked previously opened at 10am.

**Comment by dymanoid** [comment]
Currently, there are four working hours "waves":

- early first shift
- first shift
- second shift
- night shift

Having that and the overtime setting, there are more than enough ways to configure the citizens working behavior. I don't think that making **Real Time** even more complex would give the players any benefits.

I cannot believe that 90% of your citizens are starting work at the same time. For that being true, you'd need to have **only** first shift active and **only** generic industry buildings. That is just impossible.

**Comment by willbattel** [comment]
I am only using generic industry, and it does appear that only the first shift is being used despite me using default settings.

Anyway, we'll just have to agree to disagree. Thanks for discussing it, and thanks for the mod!
