### ISSUE TITLE
Industries DLC

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#181]
There's multiple types of building per industry type, forming [supply chains](https://forum.paradoxplaza.com/forum/index.php?threads/cities-skylines-industries-dev-diary-3-supply-chain-part-1.1123961/).

* **Main building**
    * Defines the industry district type (bit like park gates in park districts)
    * Can [level up](https://forum.paradoxplaza.com/forum/index.php?threads/cities-skylines-industries-5-industry-area-levelling.1124225/) (based on district level)
        * Maybe high-level farms and forestry could stop sleeping at night to handle the increased demands?
    * Info panel could potentially be used for district-level settings if desired
* **Auxiliary buildings**
    * Worker "barracks" (ugh!) and Industry maintenance
    * Increases performance of other buildings in same district
    * Sleep pattern would be derived from that used for resource extraction/production....
* **Resource extraction / production**
    * Generates raw materials
    * Existing RT industry approach should work fine for these:
        * Extraction (oil/ore) = never sleep
        * Production (farm/forest) = sleep at night
* **Raw material storage**
    * Storage for output of extraction/production buildings (and external raw resources)
    * Default to always awake
    * Will need to wait for DLC release to determine whether sleep is applicable
* **Resource processing**
    * Converts raw materials (from production/extraction or raw storage) in to special goods
    * Will need to wait for DLC release to determine whether sleep is applicable
* **Warehouse**
    * Stores special (processed) goods
    * Defaults to always awake
    * Will need to wait for DLC release to determine whether sleep is applicable
* **Unique factories**
    * Convert special goods to luxuries
    * Default to always awake
    * Will need to wait for DLC release to determine whether sleep is applicable
    * ...as only one instance of each can exist on the map, maybe per-building sleep config via building info panel?

There's mention, but insufficient detail, of new cargo services. Not sure what those will be yet, although they are definitely adding air cargo service.

There's also a new [postal service](https://forum.paradoxplaza.com/forum/index.php?threads/cities-skylines-industries-dev-diary-1.1123429/) which from what I've read will have a sorting office - the building itself would ideally not sleep, but deliveries would mostly take place during "awake hours". Possibly provide control by budget slider, if there is one?

**Comment by dymanoid** [comment]
The new industrial buildings' behavior will be mapped to the "old industrial" buildings.
In **Real Time**, there will be no differentiation between "resource extraction/production", "warehouse", "processing" etc. Otherwise, this will affect the logistics/economy, what **Real Time** always tries to avoid.
The postal service will be mapped to public transport (24/7).
No additional changes in **Real Time** are currently planned.

**Comment by dymanoid** [comment]
Implemented in [1.17](https://github.com/dymanoid/RealTime/releases/tag/1.17).

**Comment by aubergine10** [comment]
Just for clarification, the warehouses will be open 24/7 - even if they are farming/forestry specialised?
