### ISSUE TITLE
More people outdoors in nice weather?

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#182]
When it rains, people rush indoors...

Can the opposite be done when weather is particularly nice (above, say, >= 24 Celsius)? People would be more inclined to visit parks, go on walking tours, etc., and less inclined to shop, resulting in visibly more people using outdoor leisure facilities.

This could potentially be implemented via a temperature check when a cim is set to go shopping; if weather is nice, there is increased chance a cim will go to park instead of shops. As weather gets warmer, that chance could increase, sending larger percentage of cims to parks. If weather gets too hot (eg. over 34 Celsius) the chance would start diminishing again (and could even make people leave parks to avoid sunburn).

I have no idea how this would affect commercial buildings; not enough customers?

**Comment by dymanoid** [comment]
I don't think this is worth implementing. We have to fight with large citizens traffic already (see #165), so increasing citizens number that go out will cause even more problems.

**Comment by aubergine10** [comment]
#187 might be better approach in that case - if ambient sounds could be affected by time period (shift), day/night, weather, etc., simply playing more 'energetic'-sounding audio would give a sense of more outdoor activity without running in to problems associated with #165 .
