### ISSUE TITLE
Possible issue with ore/oil depletion

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#183]
Based on [a post I saw on steam](https://steamcommunity.com/workshop/filedetails/discussion/1420955187/1726450077644655685/?tscn=1539760435); I've got unlimited resources enabled so obviously haven't seen this myself.

**Describe the bug**

> The only thing i noticed is that recourses get depletted within one day - yea, that can be cured with just turning infinite recourses on, but still :/

Maybe rate of resource consumption needs linking to average (between day/night) RT game speed?

**Additional mods**

n/a

**Game log file**

n/a

**Screenshots** (optional)

n/a

**Comment by dymanoid** [comment]
**Real Time** does not affect resource extraction, logistics, and processing in any way.
Of course, if you play e.g. at speed 2, there is a possibility that resources will be depleted within one day. But this is how the game works, it's not only about resources.

**Comment by originalfoo** [comment]
Correct, RT doesn't currently change anything in that respect, but perhaps it should?

Anyone not using the base game infinite resource mod would expect that resource extraction rate would "make sense" when RT is applied. If RT adjusted extraction rates based on speed setting, that would be a good thing, particularly with all the attention Industries are getting at the moment.
