### ISSUE TITLE
Option to turn of path lights in parks that close at night

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#184]
The ability for parks to sleep at night (via "Night tours" setting) is great. However, their pedestrian path lights remain on regardless.

Would it be possible to have a new setting, specific to each park, that determines whether path lights get turned off when the park sleeps at night? For UI, it could be a radio button on the "Main Gate" for the park, or even a custom park district policy? "Lights out when park is closed"

The reason I desire the feature to be park-specific is that lots of my parks, which shut at night, double up as paths between key areas of my city - so I'd want their path lights to stay on (as per current functionality). However, I have other parks - zoos and theme parks in particular, but also a few of the other types - where I want them to go dark so they look "fully closed to the public" at night.

The lights would still come on at sunset. When park closes at night (night tours = false), if the additional option (turn off path lights) is set then the path lights would go off again and stay off until the park opens the next day (possibly resulting in lights coming on if it's before sunrise).

Ideally, when turning off ped path lights in a park, it would happen about an hour after the park closes rather than immediately. In the morning, the lights could potentially turn on an hour before park opens too? It would be sweet if in those "maintenance hours" (one at night, one in morning) the park maintenance vehicles could show up...

Road and other network lights would remain unaffected, as would individually placed light props within the park area. It's only the ped path lights that would go out.

**Comment by dymanoid** [comment]
This is a very special feature. It might add some realism, but in fact it is so negligible that I'm skeptical about it.

**Comment by aubergine10** [comment]
I'm not sure it's negligible considering the map is viewed from above most of the time and, at night, lights are the most visible indicator of city activity. This ties in with the discussions in #180 (weekday vs. weekend) and #187 (ambient sounds), and bears in mind the limitations relating to #165 (citizen limit)...

As cities grow, it becomes harder to see the effects of RT based on citizen activity alone, especially from above. Having park and residential buildings go dark really emphasised night time aspect of RT because there's very obvious visual difference. This embellishment would extend that trope.

Another good example is marinas and other shoreline areas - they're usually excessively lit in evenings, but lights go out around 2-3am (assuming the area closes for the night).

As there's a limit of 256 park areas (I think?) and most parks will leave lights on, there wouldn't be much extra bloat in save games; Persisted array would list only the "lights out" park ids (8 bits per id, so max ~2kb if all parks were "lights out").

**Comment by dymanoid** [comment]
I would keep the pathways and alleys lit though. I think this is even more realistic than turning them off - in my city, all parks keep the path lights on all night long although all the buildings and facilities are indeed closed.

**Comment by aubergine10** [comment]
Yes, true, in city centre the lights will stay on.

But in rural locations, waterfronts (often), and nature reserves, the lights go out.

In AMAs, CO has mentioned a few times that they would consider doing a beach/waterfront DLC, at which point there would likely be a dedicated park or district type.

Maybe put this issue on hold until the next DLC and revisit after that? Although, in interim, it would be great if nature parks could turn their lights off.

**Comment by dymanoid** [comment]
Decided to not implement this one.
From my point of view, the roads and pathways should always be lit.
