### ISSUE TITLE
Industries DLC: Reduce rate of industrial production

### ISSUE THREAD

**Issue by HongPong** [dymanoid/RealTime#185]
**Describe the solution you'd like**
There is way too fast industrial production of agriculture in the game especially. Can this rate be reduced by some number in the UI, for example 70% less production, with 70% fewer trucks generated? There is a topic here about the problem of agriculture trucks
https://www.reddit.com/r/CitiesSkylinesModding/comments/9rjzr4/request_lower_industry_dlc_building_production/

Thank you for working on this mod, I see from Steam that it is intended to be updated for industries.

**Comment by dymanoid** [comment]
**Real Time** will not affect the economy directly, so this feature request is unfortunately out of scope for **Real Time**.
Furthermore, I don't see why this feature cannot be implemented in a tiny separate mod. It has actually nothing to do with **Real Time** per se.
