### ISSUE TITLE
Changing settings manually for save (without options menu)

### ISSUE THREAD

**Issue by kevindongyt** [dymanoid/RealTime#186]
Is there a specific way to set the <VirtualCitizens> flag in the XML "Realtime.xml" file for a specific save? I've tried tuning the setting  to "Vanilla" in the steamapps/Cities_Skylines folder. but it did not work: in the save it still says "Real". On the main menu it says vanilla though...

**DO NOT ASK ME TO USE THE OPTIONS MENU IN SETTINGS.** That would be too obvious, but mine is bugged and I cannot select the options. This applies to all mods (for some bizarre reason!) If it were this easy I obviously wouldn't ask on Github....

**Comment by dymanoid** [comment]
No, there is no way. The settings file "Real Time.xml" stores the default settings only. They apply to new cities.
