### ISSUE TITLE
Fork "Ambient Sounds Tuner" mod to create RT-aware version

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#187]
Splitting this out from #180...

Currently the city sounds are same at all times of day, night, weekend vs. weekday, etc. it would be great if they could change to reflect the RT settings.

> The other issue is that we're looking at the map from above. When you're on ground IRL you notice weekend is different because of way people behave, dress, and so on. None of that can be seen from up in the air. I think that's the ultimate problem. RT could jump through hoops to make weekend ever more distinct from weekdays, but from up in the air you'd never really "experience" it.
> 
> The only thing I can think of would be tweaking the ambient city sounds at weekend, but that's out of scope of RT, IMO. Maybe a fork of the Ambient Sounds Tuner mod that allows different sounds for weekday, weeknight, weekend?

RT would then cause different city sounds during the different times of day. The user would be responsible for installing sound pack mods and choosing which sounds to play at different times.

An option for "None" (no sound) would also be beneficial. For example, residential areas could become silent during sleep time. Farms could have distinct day vs. night sounds, and so on.

I think this would really take the RT effect to a new level, making gameplay more immersive and emphasising the distinction between day/night, and weekday/weekend, where applicable.

In addition, the Ambient Sounds Tuner mod hasn't been updated in ages, it's missing lots of settings for DLCs and even base-game stuff.

**Comment by originalfoo** [comment]
Weather could also affect the sounds; for example, people go indoors during rain, so sounds should change.

**Comment by dymanoid** [comment]
This is indeed something for a new mod. Incorporating all this into **Real Time** will make it unnecessarily complex. I will introduce a new label "mod suggestion" and mark all related issues with that.
