### ISSUE TITLE
Info: DLS3 mod has been updated to use harmony

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#194]
Just an FYI:

> -- 2018-12-11: Harmony update. Code rewritten & tested by egi and t1a2l. Should fix a lot of  problems/incompatibilities with other mods. Big thanx to you guys!! --

Hopefully it's improved compatibility between DSL3 and RT.

**Comment by dymanoid** [comment]
Checked the **DSL3.0** source code and confirmed that it is now compatible with **Real Time**.
