### ISSUE TITLE
(new mod) Resources for construcions

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#200]
There's a mod in workshop called [RealConstruction](https://steamcommunity.com/sharedfiles/filedetails/?id=1614061108) by @pcfantasy that requires resources from industry to complete a construction. If resources run out, the construction stalls until more deliveries are made.

Source on github: https://github.com/pcfantasy/RealConstruction

It doesn't seem to integrate with RealTime, which has it's own alterations to construction (eg. prevent construction at night time).

Would be nice if the mod could integrate with RT, or maybe even be incorporated in to RT?

I realise this is probably out of scope of RT and thus needs "new mod idea" tag.

**Comment by pcfantasy** [comment]
@aubergine10

OK, I can update my mod to read realtime options and prevent construction at night time

**Comment by aubergine10** [comment]
@pcfantasy I didn't check yet whether your mod requires **wood** resource; if so, note that in RT the forestry (and farming) industry is closed at night. Oil and ore work 24/7.

**Comment by dymanoid** [comment]
I don't think that **Real Time**'s options need to be considered at all. **Real Time** patches the `PrivateBuildingAI.GetConstructionTime` method that causes the construction to stop at night (because the speed is 0). This is all done by the game itself. The only thing **Real Time** does is setting this customized construction speed.

**Comment by aubergine10** [comment]
In the morning, however, RT sets the construction speed to a value derived from RT mod settings, eg. I could have construction be very slow (it could take a few days to construct big building), IIRC?

Any mod interfacing would need to look at the RT settings to determine what speed should be used when construction resumes at any point.

Also, in morning, RT might resume a construction that was paused due to lack of materials the day before?

**Comment by dymanoid** [comment]
No, the construction speed is decoupled from the time speed. It is set in frame-based units (0 to 1088). 0 means "instant construction", 1088 is the slowest. Any value greater than 1088 means "paused". These are CO's original frame based values.
There's no need for other mods to "observe" the construction speed or the daytime. Instead, other mods should just check the speed value each simulation frame - easy as that - and perform their actions accordingly.

**Comment by dymanoid** [comment]
Oh, I see that mod doesn't use Harmony. Well, this is going to be a tough one. I think, we might even have a mod incompatibility here.

**Comment by pcfantasy** [comment]
@dymanoid 

I see, there is no need for me to change mod, I detour **PlayerBuildingAI**.GetConstructionTime, not PrivateBuildingAI.GetConstructionTime, so there is no confict.

And for PrivateBuilding, even get enought resource, at night, RT will still stop this construction, so no issue there.

**Comment by dymanoid** [comment]
@aubergine10, do you encounter any issues when using both mods together? What exactly do you mean by 

> doesn't seem to integrate

?

**Comment by aubergine10** [comment]
It was building skyscrapers at 3am. I've currently got most mods disabled due to testing some stuff for TMPE, but will test again later this week (probably around Thursday/Friday) and report back if the issue is still happening.

**Comment by aubergine10** [comment]
Hey, sorry for taking so long to come back on this issue. I've not been able to reproduce it, so either it was just me being stupid or something changed that fixed the issue. In any case, I think this issue can be closed unless there is some other discussion required?
