### ISSUE TITLE
FYI: Attaching a debugger to running game

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#201]
This might be of use - ability to attach a debugger to mono:

https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Attaching-Debugger-to-Cities-Skylines

Via: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/60

**Comment by dymanoid** [comment]
Thanks for sharing. However, I already know this technique.
