### ISSUE TITLE
Citizen not found!

### ISSUE THREAD

**Issue by pcfantasy** [dymanoid/RealTime#209]
**Describe the bug**
A lot of Citizen not found in output.log, if disable RealTime mod, all thing is fine.
I debug this for a while, it seems RealTime and TMPE release citizen instance twice?
You can use harmony to add blow codes to monitor this strange behaviour.

        public static void CitizenManagerReleaseCitizenInstanceImplementationPreFix(ushort instance, ref CitizenInstance data)
        {
                if (data.m_flags == CitizenInstance.Flags.None)
                {
                    DebugLog.LogToFileOnly("Error: release a already released citizeninstance" + Environment.StackTrace);
                    DebugLog.LogToFileOnly("m_sourcebuilding = " + data.m_sourceBuilding);
                    DebugLog.LogToFileOnly("m_targetbuilding = " + data.m_targetBuilding);
                }                
     }

**Additional mods**
You can get all the mods you needed in save file

Enabled Plugins:

- Unlimited Money
- Unlimited Oil And Ore
- Unlimited Soil
- Unlock All
- Prop Precision 1.0.1
- Prop Snapping
- Find It! 1.5.4
- Klyte Commons 1.1.6
- TM:PE 10.19
- Fine Road Anarchy 汉化版1.3.5
- Move It! 汉化版 2.1.3
- AutoLineColor Redux
- Touch This! Tool 2.0.2
- Improved Public Transport 2 [r4.2.2]
- Improved Content Manager
- Extended InfoPanel (0.8.2)
- Prop Line Tool
- LoD Reducer
- Elevated Stops Enabler
- Improved Wind Simulation
- Remove Need For Power Lines
- Daylight Classic
- More Beautification
- Building Themes
- Unlimited Trees Mod
- Remove Need For Pipes
- More Effective Transfer Manager
- Real Time
- Network Extensions 2
- Loading Screen Mod
- WG Citizen Lifecycle Rebalance v2.6
- Fine Road Tool 1.3.7
- Automatic Bulldoze v2
- Prop & Tree Anarchy
- Network Skins
- Extra Landscaping Tools
- Power Balance
- WG Realistic Population v8.4.0
- Enable Achievements

**Game log file**
See attachment

[output_log.txt](https://github.com/dymanoid/RealTime/files/3144493/output_log.txt)
[test5.zip](https://github.com/dymanoid/RealTime/files/3144486/test5.zip)

**Comment by pcfantasy** [comment]
@dymanoid 
I think I find the root cause.

You have a postfix to add ProcessWaitingForTransport() in ResidentAI.SimulationStep.
In ProcessWaitingForTransport(), if a citizen is homeless, you will release this citizen.
But after  ResidentAI.SimulationStep, there is still other codes in HumanAI.SimulationStep to release citizens. Which will cause this issue.

I will modify this and test this fix, then give you a pull request for your review, thanks.

		private sealed class ResidentAI_SimulationStep : PatchBase
		{
			protected override MethodInfo GetMethod()
			{
				return typeof(ResidentAI).GetMethod("SimulationStep", BindingFlags.Instance | BindingFlags.Public, null, new Type[]
				{
					typeof(ushort),
					typeof(CitizenInstance).MakeByRefType(),
					typeof(CitizenInstance.Frame).MakeByRefType(),
					typeof(bool)
				}, new ParameterModifier[0]);
			}

			private static void Postfix(ushort instanceID, ref CitizenInstance citizenData, ResidentAI __instance)
			{
				if (ResidentAIPatch.RealTimeAI == null || instanceID == 0)
				{
					return;
				}
				if ((citizenData.m_flags & (CitizenInstance.Flags.WaitingTransport | CitizenInstance.Flags.WaitingTaxi)) != CitizenInstance.Flags.None)
				{
					ResidentAIPatch.RealTimeAI.ProcessWaitingForTransport(__instance, citizenData.m_citizen, instanceID);
				}
			}

**Comment by dymanoid** [comment]
It turns out that 'releasing' a (resident) citizen, when their home building is not set, is generally wrong. The game will e.g. try to find a new home for a citizen whose housing was demolished.

I completely remove the releasing code for that part.

The game must cope with those citizens (either provide a new home or 'release' them). According to my tests, there are no negative effects in removing of the releasing code.
