### ISSUE TITLE
Campus DLC & patch incoming.....

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#211]
Looks like load of new education stuff...

![1557417889_ghghghgh](https://user-images.githubusercontent.com/1386719/57471337-df595780-7282-11e9-9b9e-a3982f88a34e.png)

* Sports = rebrand of existing concerts / match day features
* Districts = guessing they work like industry / park districts
* School bus = players will be expecting this to transport students
    * Don't yet know if this is also intended for sport events transport
* Note the year cycle too, that is likely something new

https://store.steampowered.com/app/944071/Cities_Skylines__Campus/

**Comment by dymanoid** [comment]
Thanks for the info. Real Time will be updated on Steam on the release day and thus will be 100% compatible with the new DLC.
