### ISSUE TITLE
Cim education after Campus update broke the flow of this mod

### ISSUE THREAD

**Issue by AngryScandinavian** [dymanoid/RealTime#219]
https://steamcommunity.com/app/255710/discussions/0/1640912759107682620/?tscn=1559167184
Relevant discussion on the steam discussions page 

I tried to explain that this was something that probably cannot be fixed on Real Time's part but several people were insistent that I bring this here.

To be brief:
The changes to Cim education in the Campus patch means that initial citizens cannot be educated so you are stuck for a **LONG** ass time with low land value and low level structures because of how long those initial citizens last.
I am not sure how long Cims lives are supposed to be in this mod. I have "better aging and birth rate" enabled and the time speeds are set to 5. I left for the movies with the game on maximum simulation speed to allow those "uneducate-able" people to have kids and die off. So far I've waited a cumulative 12 or 13 hours of AFK under these conditions and the 50% of my population that are adults are still completely uneducated (meaning they were the initial citizens). 
I have education boost / educational blimps and double the adequate cim capacity for education to occur so any adults that were created in that AFK period (about 6% of my population) have been educated successfully.

**Comment by dymanoid** [comment]
I close this as a duplicate. See the referenced issue.
