### ISSUE TITLE
Bus dissapear after spawning from the bus depot

### ISSUE THREAD

**Issue by sedna6633** [dymanoid/RealTime#226]
Have been testing the mods which are causing the bugs, and it turns out to be this real time mod. Maybe after the campus update, this issue start to appear. 

The buses did spawn, but they disappear when entering the road in front of the depot.

[output_log.txt](https://github.com/dymanoid/RealTime/files/3309406/output_log.txt)

**Comment by dymanoid** [comment]
Thanks for reporting, but this simply cannot be caused by Real Time.
Real Time doesn't affect the game vehicles (including public transport).

This might be caused by traffic related mods (like TM: PE, IPT2 etc) or by a road network mod.
