### ISSUE TITLE
Error when loading a city

### ISSUE THREAD

**Issue by LazoYoung** [dymanoid/RealTime#227]
[message.txt](https://github.com/dymanoid/RealTime/files/3323886/log.txt)
I get this error message whenever I load a city (both new and existing ones).
Clearly, I have disabled all the other mods, but it doesn't help.
I believe that I'm using the latest version of the game and this mod.
Could you address what is the cause of this?

**Comment by dymanoid** [comment]
The error message in the log states, that a file cannot be found. This is not a Real Time issue.

Have you tried to open the folder "D:\Program Files\Steam\steamapps\workshop\content\255710\1420955187" in Windows Explorer?

The folder contents should look like this:
![realtime](https://user-images.githubusercontent.com/9433345/60119303-66548780-977e-11e9-8dd0-6b4471b7eb77.PNG)

If it doesn't, then something went wrong on installing the mod. Try unsubscribing and re-subscribing again. If it doesn't help - well, seems your Steam client is broken.

If the folder content look okay, try to find another "0Harmony.dll" files in the Workshop folder. Maybe you have installed some mod that deploys an incompatible version of that library.

Note that disabling the mods won't help. The game still loads all disabled mods, and lots of them are implemented badly - they affect the game even when they are disabled.

**Comment by LazoYoung** [comment]
I really appreciate your kind response, I'll try it now

**Comment by LazoYoung** [comment]
I checked out the workshop folder and there was nothing actually missing or conflicting.
But re-subscribing the mod simply fixed the problem. I guess my steam client was corrupted during the installation phase like as you suggested.
