### ISSUE TITLE
Workers in vehicles and at work

### ISSUE THREAD

**Issue by t1a2l** [dymanoid/RealTime#237]
Right now when you plop a bus depot, buses just spawn and drive around regardless of people actually work there or not (any service works the same) - I want to interduce a new mechanic - people should come to work in one of the services (actually take a ride and go there), Some of the workers would be drivers, and if you follow them you will see them inside a bus or garbage truck or taxi. I think it will add realisem to real time, so if you don't have enough people there will be no services, or not enough police cars on the street.

**Comment by dymanoid** [comment]
See [this](https://github.com/dymanoid/CitiesSkylinesModWishList/issues/17) issue. I wanted to implement it first, but then decided to put on hold. This would make the game very difficult to play and totally unplayable for large cities (due to #165).
