### ISSUE TITLE
My companies and factories were bankruptcy and abandoned in night

### ISSUE THREAD

**Issue by zkx741481546** [dymanoid/RealTime#247]
Because of lack of buyer

**Comment by dymanoid** [comment]
Which version of Real Time are you using? Your description is pretty vague. Could you please elaborate?

**Comment by dymanoid** [comment]
@zkx741481546 Any news on this?

**Comment by dymanoid** [comment]
Closing due to no feedback. If the problem still exists, the issue can be reopened.
