### ISSUE TITLE
Issue with some amusement park buildings not lighting

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#248]
> I've currently got these buildings in a "City Park" park area rather than their usual amusement park area (amusement main gate is too big for the beach where I've put the buildings). Would that make a difference?

Drop tower ride:

![image](https://user-images.githubusercontent.com/1386719/70378200-a6b35680-1915-11ea-816c-f6688d06c229.png)

Base lights not coming on:

![image](https://user-images.githubusercontent.com/1386719/70378224-dc583f80-1915-11ea-8b05-328b42d5d387.png)

Also, only the rightmost arcade lights up; the one on the left never lights up:

![image](https://user-images.githubusercontent.com/1386719/70378237-07db2a00-1916-11ea-833e-00f4b7b9479a.png)

Likewise, the swinging boat never lights up:

![image](https://user-images.githubusercontent.com/1386719/70378256-1c1f2700-1916-11ea-9862-17fb54cd9ec1.png)

In-game time is 9:30PM; most other stuff in the city has lit up:

![image](https://user-images.githubusercontent.com/1386719/70378274-512b7980-1916-11ea-8f39-4802d34feeb5.png)

**Comment by dymanoid** [comment]
Is this a permanent issue or time-depending? Does it also occur without Real Time? Which building status is shown in the building info panel ("active"/"not active")?

**Comment by aubergine10** [comment]
It's consistent each night. The buildings are marked active and still animate. I'll do some more testing w/ and w/o RT...

**Comment by aubergine10** [comment]
Amusement buildings (those mentioned above, not tested others yet) in _city_ park area:

* "Operating normally"
* Unlit

Amusement buildings in _amusement_ park area:

* "Not operating"
* Unlit

I had some light props disabled in LSM `skip.txt`, but commented them out and disabled that feature of LSM; no difference.

Will test again next game evening to see if there's any difference in the amusement park area.

**Comment by aubergine10** [comment]
Still having this problem; I disabled LSM to see if that was cause, but issue peristed. I'm going to do some testing next time in-game to disable Real Time and see if the lights come on (if not then I know it's some other cause, otherwise I'll know RT is somehow involved).

**Comment by dymanoid** [comment]
@aubergine10 Any news on this?

**Comment by aubergine10** [comment]
The problem is still there but UI have not been able to find any obvious cause yet. I'll see what happens once the dust settles from Sunset Harbor update.

**Comment by aubergine10** [comment]
Is there any way to trigger debug trace on the buildings?

FYI the save is in workshop (but has 4.5k+ assets and 140+ mods so will be pain to test): https://steamcommunity.com/sharedfiles/filedetails/?id=2056376792

**Comment by aubergine10** [comment]
I've started new city now so closing this issue. Would be useful to have some sort of debug mode in future though.
