### ISSUE TITLE
Extremely low commercial demand after using Real Time mod

### ISSUE THREAD

**Issue by qdb99581** [dymanoid/RealTime#249]
Like what title says, after using this mod I have found that my commercial demand is almost zero, that leads to my city almost can not build a downtown.

my commercial demand is as shown below
https://imgur.com/LaLupB4

And it's not just me have such a problem, the situation is also been discussed on the forum of Steam. We really love this mod so we hopefully that bug be fixed, thank you!

**Comment by dymanoid** [comment]
*"This is not a bug, this is a feature". *

You have to re-think your approach for building a city with Real Time. The demand depends on how often citizens go shopping, and Real Time changes a lot in citizens' behavior.

There were many cities reported with population even >400.000, built with Real Time.
