### ISSUE TITLE
Buglet: Service vehicles immediately returning to buildings

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#253]
I've been having this issue for a while, intermittently: For a few minutes _after placing a new service building_, the vehicles that spawn from it leave the building but then turn round and immediately go back to the building and despawn. After some minutes (not sure quite how long) the building becomes properly operational and works normally thereafter.

So far I've seen it happen with:

* Fire engines
* Police (cars and helicopters)
* Disaster helicopters
* Ambulances
* Hearses
* Garbage trucks

Next time I see issue occur, I'll post game logs and any other relevant details.

A user on Steam ([Discussion](https://steamcommunity.com/app/255710/discussions/0/1750147465521623513)) was having same problem as me and tracked it down to Real Time mod (it could be some other mod conflicting with Real Time). I've asked them to share their logs, etc., in the hope that comparing with mine (which I'll share next time I'm in-game) might narrow down list of likely causes.

**Comment by dymanoid** [comment]
I am struggling to imagine how Real Time could affect the service vehicles dispatching.

I will need to investigate this.

**Comment by ihatearial** [comment]
Don't know if that helps but when this happens, I use "delete vehicle" button and then they stop doing that, in helicopters.
The pattern with vehicles looks like they to try to find a route and get back to their original building. After some time they get back to normal.

**Comment by dymanoid** [comment]
This issue might be fixed in b6ac8512921a9b97c3e6c17489cda3b6696bda6e.

**Comment by aubergine10** [comment]
I'll be spending lots of time in-game this week so I'll see if I can reproduce it with that update.

**Comment by aubergine10** [comment]
I'm not seeing this issue currently - so whatever caused it seems to be fixed. 

Also, an additional cause is identified: `TransferManager` making requests to a service building that is unable to reach destination (this primarily for road vehicles of course).
