### ISSUE TITLE
Possible bug? base.CitizenProxy.SetVisitPlace not work

### ISSUE THREAD

**Issue by pcfantasy** [dymanoid/RealTime#255]
I know, it sounds strange, but after Real Time lets a resident `StartMovingToVisitBuilding`, I use the below code to calculate all incoming visitors for a commercial building:

```C#
Citizen.BehaviourData behaviour = default(Citizen.BehaviourData);
int alivevisitCount = 0;
int totalvisitCount = 0;
GetVisitBehaviour(targetBuilding, ref building, ref behaviour, ref alivevisitCount, ref totalvisitCount);
```

But I cannot find those citizens which are heading to a commercial building and are on their way.

After adding a postfix patch to `ResidentAI.StartMoving`, the problem is solved.

```C#
public static void Postfix(uint citizenID, ref Citizen data, ref ushort targetBuilding, ref bool __result)
{
    if (__result)
    {
        data.SetVisitplace(citizenID, targetBuilding, 0u);
    }
    else
    {
        data.SetVisitplace(citizenID, 0, 0u);
    }
}
```

So I think the `base.CitizenProxy.SetVisitPlace` is not working in `StartMovingToVisitBuilding`?

**Comment by dymanoid** [comment]
There is nothing special in this method, it is just a proxy to `Citizen.SetVisitPlace`.
If it wasn't working, there would be a lot of issues with the game.
I suppose a mod conflict here. Have you tried to set a break point into the `Citizen.SetVisitPlace` method and to look if it gets properly called by `StartMovingToVisitBuilding`?

**Comment by pcfantasy** [comment]
@dymanoid 

Yes, I understand, I will clone your mod, and do some test on this method, will give you feedback then.

**Comment by pcfantasy** [comment]
@dymanoid 
Sorry.  I use alivevisitCount, so it will not count those citizens are on their way.  TT

GetVisitBehaviour(targetBuilding, ref building, ref behaviour, ref alivevisitCount, ref totalvisitCount);
