### ISSUE TITLE
Possible bug or Design intent? commercial will not add shopping outgoing offer

### ISSUE THREAD

**Issue by pcfantasy** [dymanoid/RealTime#257]
public bool IsShoppingTarget(ushort buildingId)
        {
            if (buildingId == 0)
            {
                return true;
            }

            // A building still can post outgoing offers while inactive.
            // This is to prevent those offers from being dispatched.
            if (!buildingManager.BuildingHasFlags(buildingId, Building.Flags.Active))
            {
                return false;
            }

            var buildingService = buildingManager.GetBuildingService(buildingId);
            return buildingService != ItemClass.Service.VarsitySports
                && buildingManager.IsRealUniqueBuilding(buildingId);
        }

@dymanoid 

It seems you do not let commercial building to add shopping outgoing offer. Only UniqueBuilding **&&** buildingService != ItemClass.Service.VarsitySports can send shopping outgoing offer.

Is this what you whated?

**Comment by dymanoid** [comment]
Thanks for spotting this. It is indeed a bug.
