### ISSUE TITLE
Incorrect units regarding water (m^3/10min)

### ISSUE THREAD

**Issue by James103** [dymanoid/RealTime#265]
Real Time v1.20.1; Cities Skylines v1.13.0

I think that the units of water are incorrect. When the Real Time mod, the time units of "... per week" are changed to "... per 10 minutes", but the units of m^3 for water are left unchanged. This causes the water production and usage to appear to be 1,008 times whatever it was before the Real Time mod. To fix this, every instance of m^3 in water and sewer should instead be replaced with liters (L). One liter is 1/1000 of 1 cubic meter, which brings things back in line.

**Comment by dymanoid** [comment]
I don't quite understand the issue.

The original units are "per week" (in terms of time). The new units are "per xxx minutes" (in terms of time). Real Time only changes the time flow in the game.

Why should we change the volume units as well?

**Comment by Dushess** [comment]
It is able to work as for ingame weeks (no dependencies from settings), right?

**Comment by dymanoid** [comment]
No, the statistics cannot be changed. The statistics gathering is based on the simulation speed, not on the time speed. So, Real Time cannot change the time units for the statistics.
It will just stay as it is: the time units will be "40 min" / "20 min" / "10 min" etc depending on the time speed configured in the Real Time options.

**Comment by Dushess** [comment]
Ok, there is need an override as independent mod. Maybe...
