### ISSUE TITLE
Must be subscribed to Workshop

### ISSUE THREAD

**Issue by jpwyze** [dymanoid/RealTime#266]
Hello! dear creator Dymanoid. I really appreciate your work which is awesome, i don't have the words to explain it, cause just by looking at it i can imagine that you worked really hard to make this beautiful mod. I'm sorry to bother you here, but i don't know how to contact you otherway.  

I'm begging you if is not much trouble for you to make this mod free to take off the subscribed mod part, to be used offline steam... or at least if you can take it of for me, privately, i'm paying for it if you really want to show my appreciation toward your hard work cause I want to support your work and your help. I know this is maybe a troublesome request for you, but i want very much to enjoy your beautiful mod. Sadly I tested the Real time OFFline but I believe when i activated it i had the error : Field '.Citizen.m_age' not found. [System.MissingFieldException] Details: No details
and without the mod I did not have this error, you said maybe is cause of the mod "'dropouts" but i don't have it installed so maybe is another mod that is not compatible with? i don't know... That's why I want to try your mod which is updated in hope to not have this error on the offline real time... 

I hope you can help me and anyway..  Thank you again very much for everything you've done by creating this mod in the name of every player!

**Comment by dymanoid** [comment]
Thanks for reaching out!

I publish the Real Time binaries on Steam Workshop only, so this published version will always require a Steam subscription. You don't need to be online though, you can indeed play offline.

If you don't like that, you can get the source code of Real Time (it is public and free) and change it by yourself, you don't need me for that. If you can't program and don't want to dive into software development, you can ask a friend to do that for you.

**Comment by jpwyze** [comment]
I tried that but i have some problems when i try to compile it.  
![image](https://user-images.githubusercontent.com/63015691/78177262-24b7e200-745e-11ea-8f9d-1dc0f2c33fcf.png) I dunno how to fix it.. so i can compile in DLL fille.

**Comment by dymanoid** [comment]
You need a git repo to build the solution. Seems like you just downloaded the code as a zip file - that won't work. You have to clone the repository.

**Comment by jpwyze** [comment]
Thank you a lot! I managed to make it work! Was hard for a beginner as myself but, i did it!   thanks again. Only problem is that I can't see the text ^^" the mod seems to work fine but I don't know how should I make the mod to read the translations. 
![image](https://user-images.githubusercontent.com/63015691/78186935-dad6f800-746d-11ea-9895-2351bce917a0.png) i'll try to figure on my own but if i can't well i'm still happy that i don't have the error bug "citizen.m_age" anymore ! thank you!! and sorry again for bothering you!

**Comment by HannesJo0139** [comment]
Pretty funny how Dinamoid pretends that the Steam Workshop is automatically necessary, since it is published in the workshop. Fact is, he has a query built into the mod. So Dinamoid explicitly forbids the use without Workshop. You don't need to understand the reasons. I do not.

But you can get around it without compiling the whole package yourself. Much too time consuming. We are dealing with .NET software here. So the .dll can be edited quite easily with the tool "dnSpy".
