### ISSUE TITLE
Time scaling for Editor

### ISSUE THREAD

**Issue by Dushess** [dymanoid/RealTime#269]
Not really an issue, but can RT use time passing override also for editor? There is no simulation obviously, but stock speed screws up date very quickly for selected city map. 2693 year at just one real day of city handling is very weird.

**Comment by dymanoid** [comment]
You can use other mods to explicitly set the date in the game.
Real Time will not be available in the editor mode.

**Comment by Dushess** [comment]
dumb question, actually..... They added autopause to the game. also just ignore this.
