### ISSUE TITLE
Simulation in Editor is broken by some reason (?)

### ISSUE THREAD

**Issue by Dushess** [dymanoid/RealTime#272]
Occasionally turned it on, closed the whole game due to nothing more to do from bunch error messages. They can be clicked out, but very nervious. And or course no citizens yet, since it is not created and prepared yet.
**Please check if it can be related to your mod.**
```
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Simulation error: Field '.Citizen.m_age' not found.
  at ThreadingWrapper.OnAfterSimulationFrame () [0x00000] in <filename unknown>:0 
  at SimulationManager.SimulationStep () [0x00000] in <filename unknown>:0 
  at SimulationManager.SimulationThread () [0x00000] in <filename unknown>:0   [Core]
```

Enabled mods can be found in my collection: https://steamcommunity.com/sharedfiles/filedetails/?id=1844996846

TMPE last lines is 
```
Info 4,170.0223184: ThreadingExtension.OnBeforeSimulationFrame: First frame detected. Checking detours.
Info 4,170.0362729: ThreadingExtension.OnBeforeSimulationFrame: First frame detected. Detours checked. Result: 0 missing detours
```

**Comment by Dushess** [comment]
Few of them is disabed, but related to other things that any simulation handling.

**Comment by dymanoid** [comment]
This issue is not caused by the current Real Time release. The exception cause is a failing access to a missing field in a class.
Also, I am not sure how TMPE log file is related to Real Time.

**Comment by Dushess** [comment]
Just seen troubles with this mod, already switched to other branch. Thanks for answer.

**Comment by Dushess** [comment]
I am stupid, education control (same code parts to modify) and horribly outdated Dropouts (self explainatory)
