### ISSUE TITLE
Vacations for citizens

### ISSUE THREAD

**Issue by dymanoid** [dymanoid/RealTime#28]
Currently, all citizens work all the year long having just breaks on Weekends.
Like in real life, some citizens should be able to go on vacation. The maximum duration should be configurable (not all players might like when lots of workers are hanging around for 2 weeks).
The vacation probability should depend on the current season and social status. Families should go on vacation all together (including children and teens).
Citizens will visit leisure, tourist, and parks as well as go shopping. More night activity on vacation for adults.

**Comment by Sipke82** [comment]
Would be awesome, also they should goto places outside the city! (using car/train/plane)

https://www.reddit.com/r/CitiesSkylinesModding/comments/8v0bt0/request_tourism_the_other_way/

Additionally, would be cool if certain periods (summer/christmas) have increased vacation utilization :-)

**Comment by dymanoid** [comment]
This feature can be implemented only together with #57.

**Comment by nosh59** [comment]
Would it be possible to have outside tourists travel together as a family as well? I find it quite strange that a tourist child can travel to my town in an full-sized RV on his own.

**Comment by dymanoid** [comment]
@nosh59, this is not necessarily a feature for **Real Time**. I think this is something for another mod like e.g. Citizen Lifecycle Rebalance.

**Comment by Sipke82** [comment]
Could it be made that citizens who go on vacation can actually leave the city for a amount of time? 
I've always found it disappointing to see the those empty parking lots near the airfields.... And in addition that flights out of the city are mostly empty...

This argument also applies at intercity trains.
