### ISSUE TITLE
Please use harmony as the redirecting lib

### ISSUE THREAD

**Issue by DaEgi01** [dymanoid/RealTime#3]
check out https://github.com/pardeike/Harmony

it's the way to go to make multiple mods that try to change the same methods work together without conflicts.

**Comment by dymanoid** [comment]
I will take a look on that. I decided not to go Harmony (yet) because of the issue pardeike/Harmony#83.

**Comment by pardeike** [comment]
If you can explain how to make the compiler target the base class from within C# code you write inside a patch, I am more than happy to implement it. It is easy in low level IL code where you simply insert a CALL baseMethodInfo code but from C#, it seems impossible.

The main problem is that ((BaseClass)someInstance).SomeMethod() will always call the instance class and not the base class. But I am open to clever suggestions that I can implement in Harmony.

**Comment by pardeike** [comment]
Actually, after discussing it in the Harmony discord, we found that the MethodInvoker (or simply creating a delegate yourself from the MethodInfo of the method you want to call via reflections) works well and has almost no performance hit. Doing so during patch time and storing the delegate in a field makes for pretty compact and readable code too. The latest master on Harmony has a fix for MethodInvoker to access restricted methods. The v1.1.1 release is planed in the coming days.
