### ISSUE TITLE
Time warp while paused

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#30]
While game is paused, allow time warping. Return to previous time when game is un-paused.

Also, auto-pause when time warping (so I don't have to manually pause prior to time warping). Un-pausing would still be manual process.

**Comment by dymanoid** [comment]
I think, I will change the idea a bit. I introduce a new small button that switches between three states:

- **normal**: the light conditions are determined by the game time
- **overridden day**: light conditions as of 12 a.m., the game time runs independently
- **overridden night**: light conditions as of midnight, the game time runs independently

This button will only be available when the day/night cycle is enabled in the game options.

With this button, players can choose the light conditions they want e.g. for building at night and then switch back to normal mode. No game pausing is required.

**Comment by aubergine10** [comment]
Problem is I need more granular control over the sun position while time warping, particularly when detailing. For example, I often have to get it just right so the sun is shining at a certain angle down a street so as not to have the buildings casting to many shadows on the are where I'm working.

As for night time, that is simpler - just darkness with lights on is fine. Although even here, I can foresee a desire to have some control over where the moon is if taking screenshots (which I am very prone to doing at night time). Getting the moon position just right, and the resulting moonlight on buildings, etc., can make difference between a good night time screenie and a great one.

That, for me, is the best part of time warp mod - I can get the lighting conditions just right for whatever my needs are at the time.

**Comment by aubergine10** [comment]
Why not just have two states: Normal and overriden.

Normal mode:

* Sky and weather are linked to game time

Override mode:

* Sky is independent of game time - I can right click or drag around the sun/moon circle to set sun/moon position (ie. granular control over lighting conditions)
* But weather remains linked to game time

That would be perfect :)

**Comment by aubergine10** [comment]
Further thought - simply right-clicking or right-dragging on sun/moon circle would 'detach' the sky from the game time... so no need to manually set 'override' mode prior to sky warping.

The background colour of the sun/moon circle could change colour (or globe changes colour, or whatever) as visual indicator that sky warping is active.

A right-click on the globe (tile purchase button) would return to normal mode (sky becomes linked to game time).

If sky warping is not active, right-clicking the globe could enable sky warping (detach sky from time) without actually changing the current state of the sky (in essence it would be a way to "pause" the current sky condition).

Also, daytime and nighttime states would always remain linked to game time - the game could still transition to night time state (budget changes, etc) even if the sky was warped to daylight.

**Comment by aubergine10** [comment]
Rough mockup of possible visualisation depicting sky-warp mode is active - replace the globe with an 'undo' style button:

![sky-warp](https://user-images.githubusercontent.com/1386719/42547288-3381eaba-84b9-11e8-81e3-62b902b05598.png)

**Comment by Sipke82** [comment]
I think the initial idea was the best. Allow timewarp when paused. as soon as unpause, go back to original game time, simple....

**Comment by aubergine10** [comment]
For me, RealTime is about making a city behave like a city - ie. cim activity follows recognisable patterns rather than the random chaos of vanilla game. It means they go to work/school at set times, shopping at weekends and so on. There's a clear sense of work day vs. weekend, main shift vs. night shift and so on.  The sky being synchronised with that is the icing on the cake, I love it, but it's not the primary reason I use RealTime.

An "instant noon/midnight" regularly wouldn't suffice. I generally need much more specific lighting conditions hence the need to drag around (like in time warp mod) to get the sky set exactly as I want.

For example, I had to wait until 2:30pm so the sun was in just the right place to light up an underpass I was working on. Then there's the secondary need, which is getting everything just right for screenshots at night - like, a fog might start but I want to get the moon a bit lower in the sky to include it in the screen grab. Time warp mod was always perfect for that stuff, but sadly it changes the game time which sends my cims crazy if I'm using RT.

If it's possible to "instant noon/midnight" while the game is still running, it's possible to "instant any time of day or night" while the game is still running?

**Comment by dymanoid** [comment]
It is possible to decouple the sun from the time. But then, it will be not **Real Time** anymore, I just don't want to do that.

So my final decision is: I implement the originally proposed solution. The sun position may be freely changed while the game is paused. On un-pausing, the sun position resets to correspond the game time.

**Comment by dymanoid** [comment]
**Real Time** now supports time warping while paused. However, there are no controls for that in **Real Time**. The **Time Warp** or **Ultimate Eyecandy** mods can be used to warp the time. The game will be automatically paused on warping. On resuming, the time will be reverted back again.
