### ISSUE TITLE
Construction, schools, etc continue during the weekend

### ISSUE THREAD

**Issue by czsfd4** [dymanoid/RealTime#32]
Seems a slow degradation in school attendance during a weekend cycle but they should be closed. Construction is 24/7 - as well as park attendance, etc.

**Comment by dymanoid** [comment]
Can you please be more specific? Are you sure the mod is activated and there are no active conflicting mods? It looks like Real Time doesn't even work at all.

The schools are empty on Weekends, neither students nor workers go to school on Weekends. The construction sites are paused at night by default. This can be changed in the mod's settings.
The parks are less visited at night.

**Comment by czsfd4** [comment]
Mod is activated - I tested that with using the build speed slider - that
works so I know the mod is active. What I can do is disable a couple of
other mods. - I do not have any of the mods active that you listed .. but
there might be others.. will report back

**Comment by czsfd4** [comment]
Even a on a vanilla - new game - without ANY mods except RealTime it is not
working. Mod is enabled. What do you want me to collect for you to provide
you with more information?

**Comment by dymanoid** [comment]
First of all, please share your game log. Do you see the modified time bar that shows time and day of week? Does the time flow slowly?

**Comment by czsfd4** [comment]
Yes I do see the modified time bar - and yes time moves slowly - will send log

**Comment by czsfd4** [comment]
Here is the Player.log - hope it helps...

**Comment by dymanoid** [comment]
Please note that you cannot attach files to the GitHub issues. You should upload the file somewhere and post a link here.

**Comment by czsfd4** [comment]
[Player.log](https://github.com/dymanoid/RealTime/files/2167998/Player.log)

**Comment by dymanoid** [comment]
I see no error in the log file, the mod was activated successfully. There seem to be no incompatible mods in your setup too. I have no idea why it doesn't work for you. Can you maybe make a screenshot showing a high school on a Weekend day?
Is the option 'use day/night cycle' activated in your game? 
What time speed do you set for the night and for the day?

**Comment by dymanoid** [comment]
Okay. It seems that you deactivated the 'Day/night cycle' option. Of course, **Real Time** cannot work properly. If you want to use **Real Time**, please activate this option in the game settings.

**Comment by dymanoid** [comment]
@czsfd4, did that help for you? Can we close the issue?

**Comment by czsfd4** [comment]
that can be closed - thanks.
