### ISSUE TITLE
Wind turbine speed

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#33]
When the 'rate of game speed' (or whatever the correct term is) is slowed to nearly real world time, the blades of wind turbines rotate very slowly - slower than one would expect them to turn in real life.

I ended up checking the wind overlay map a few times because the turbines were rotating so slow that my brain nagging me that the wind speed must be slow today or something.

I get why it's happening, but am wondering if for sake of gameplay they could be made to rotate a small amount faster when the 'rate of game speed' is on very low setting? (I'd still expect them to slow a bit, but not to a crawl).

**Comment by aubergine10** [comment]
Note: Some assets use wind turbine template for aesthetic effect, for example...

* [Water treatment clarifier](https://steamcommunity.com/sharedfiles/filedetails/?id=1171064873&searchtext=clarifier)
* [Airport radar tower](https://steamcommunity.com/sharedfiles/filedetails/?id=904574824&searchtext=radar)
* [Maritime radar tower](https://steamcommunity.com/sharedfiles/filedetails/?id=845670468&searchtext=radar)

**Comment by dymanoid** [comment]
I cannot reproduce this issue. With the time speed set to 1 (minimum), both the wind turbines and the advanced wind turbines rotate with their usual speed.

**Comment by aubergine10** [comment]
I'll do some more testing with fewer mods to see if that is the cause.

**Comment by aubergine10** [comment]
Hrm, it seems to be an "brain illusion" for want of a better description. For some reason when I slow the rate of time to 1, my brain is thinking the turbines should rotate faster which, if anything, is the opposite of what could conceivably happen.

You are correct in that they don't change speed. It's just my brain being weird.
