### ISSUE TITLE
Gradual 'rate of time' change between day and night speeds

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#34]
I've got day speed set to 1 (almost real time) and night speed set to something much faster (can't remember exact value, but night speed is much faster than day).

When night transitioned to day, everything was fine - the 'rate of time' in game slowed down and everything continued working as normal.

However, when day transitioned to night, the sudden change in 'rate of time' from slow to pretty fast caused utter chaos.

First, there were major traffic jams because suddenly time was condensed. But then a bunch of weird stuff started happening - for example, info panels stopped working (note: Might be issue with [Extended Building Info 1.10](https://steamcommunity.com/sharedfiles/filedetails/?id=1133108993) mod), and TM:PE cargo train restrictions were skipped resulting in cargo trains in my passenger stations. After a while, everything settled and returned to normal, but it seems the sudden shift in 'rate of time' caused a spasm in multiple aspects of the game.

As such, I was wondering if rather than just switching immediately to different 'rate of time' it would be better to have a gradual 'tween' transition between the two rates? Ideally with the transition period happening in the section of the day/night cycle with the fastest speed - in my case, the transitions would therefore happen in the night phase, before dawn and after sunset, like so:

```

nnnnnTTddddddTTnnnnn

-----          -----   ↑ Faster
     \        /       
      \      /        
       ------          ↓ Slower
```

Where:

* `n` = night
* `d` = day
* `T` = transition period (happens during night in my case, because night is faster)
* `-` = rate of time (higher = faster)
* `\` and `/` = transition between rates of time

This way the change in rate of time happens smoothly rather than a sudden spasm-inducing jump.

Hope that somewhat cumbersome description makes sense lol.

**Comment by dymanoid** [comment]
This isn't technically possible. The internal time speed can only be set to values that are power of 2. So each next speed is 2 times faster than previous. It's not that gradually.
I have no idea why the other mods react so strange to the time speed change. Need to investigate.

**Comment by aubergine10** [comment]
It's as if everything started happening at once. I'm just guessing here, but suddenly cims that were going to set off to work in 30 mins in slow time suddenly had to set off like 10 mins ago in fast time - so massive onslaught of cims rushing to work and all that extra load causes weirdness to happen with other mods?

Note: My computer is a potato - 8GB RAM, old GT 640M (512MB) graphics, 2.7 GHz Intel Core i5. Oh, and 1000+ workshop assets and ~100 mods. :D It's possible that my computer just can't handle the time shift?

I have vague recollection that there's a setting in TM:PE that determines how much CPU time is allowed for simulation accuracy (particularly in respect to vehicles at or approaching junctions) - I suspect the high load caused the additional checking (eg. lane restrictions) to be skipped for a cargo train that was approaching a junction at the time.

As for the info panel popups, no idea what was going on there, although I suspect it could be related to Extended Building Information 1.10 mod thread-locking whilst waiting for metrics pertaining to its UI?

There is potentially a whole bunch of other stuff happening during the transition between day & night. Just guessing - street and building lights being turned on or off, update city stats and so on? The game would also be switching between day/night budgets (I assume) as could some mods (eg. IPT2).

IMO it would still be worth transitioning even if it's in ^2 steps - not very smooth, but still smoother than instant jump of several steps. Alternatively have the transition from slow day time to fast night time occur later so as not to clash with evening rush hour. On the map I'm playing, sunset is some time between 4:30pm and 5:00pm (can't remember exact time) - so clashes with evening rush hour.

**Comment by Sipke82** [comment]
IMO this again boils down to being able to define when "night time" starts, #41, instead of sun dawn and sun set (which should only be used for aesthetics imo).

If you can define that nighttime starts for example at 10 pm, then aubergine10's potato computer would be just fine.

**Comment by dymanoid** [comment]
As commented in #31, we cannot define a static "night time begin".

**Comment by aubergine10** [comment]
I've proposed an alternative in #31 - summarised here:

* Keep existing daytime / night time distinction, based on sunset/sunrise
* However, introduce concept of 'business day' or 'business hours', possibly defined by the 'day shift' period
* Budgets would then be based on the 'business day' (day budget = during business hours, night budget = outside business hours) rather than 'day time'

This way if sun sets at 4pm, and my cims are still at work/school, my city doesn't suddenly go in to night mode just because the sun set... they won't be forced to squeeze on to a small night bus service for example.

Admittedly, this still isn't perfect, because I'd want X hours after day shift (depends on city size and layout as to how long it takes bulk of cims to get home via PT) before kicking in the night budgets. Ugh.

**Comment by dymanoid** [comment]
Changing budgets has nothing to do with the originally posted issue. Do you still need the gradual time speed change BTW?

**Comment by Sipke82** [comment]
IMO it would be better without :-x

**Comment by aubergine10** [comment]
If time change could be staggered a little, I still think it would be beneficial.

As for the day/night budget, yes, it's separate issue, I was just brain dumping.

**Comment by dymanoid** [comment]
I decided to not implement this. Since the game time is discrete anyway, there is actually no point to change the time in multiple steps instead of one.
