### ISSUE TITLE
Make an option to set sun dawn and sunset time in the settings instead based of the map.

### ISSUE THREAD

**Issue by Sipke82** [dymanoid/RealTime#35]
Make an option to set sun dawn and sunset time in the settings instead based of the map.

**Comment by dymanoid** [comment]
This will never be implemented. Instead, I add an option to deactivate the dynamic sunset and sunrise hours, so they will always be like in the vanilla game. I guess, these times are 5 a.m. and 8 p.m.

**Comment by aubergine10** [comment]
Out of interest, does RT change sun rise and set times based on date (eg. summer gets longer days than winter)? If so that would affect shopping and leisure patterns... which would be awesome!

**Comment by dymanoid** [comment]
Yes, the sunrise and the sunset times depend both on the map's location and on the current date. Read the description ;-)

**Comment by dymanoid** [comment]
The new option will be implemented in #43.
