### ISSUE TITLE
Make Work shifts depended on sector.

### ISSUE THREAD

**Issue by Sipke82** [dymanoid/RealTime#37]
It would be more realistic if workshits would depend on sector for instance:
Industry: Shift1: 6am - 2pm Shift 2: 2 pm till 10 pm (not sure about agriculture
IT and offices : 9 am - 5:30 pm
Shops: 11 am - 8 pm
Leisure: shift 3 pm - 3 am ? in two shifts?
etc etc
Best would be if it could be user configurable, perhaps via an XML file?

**Comment by dymanoid** [comment]
While this is of course realistic, it makes the game too complicated. I'm not sure it is worth to implement this.

**Comment by dymanoid** [comment]
As of v1.2, there are already different shifts count for different building types (e.g. Industry - 3 shifts, offices - 1 shift etc.) There is a special extended first shift for some buildings too (starts early in the morning). So I think I will not over-complicate this.

**Comment by dymanoid** [comment]
Creating an overview is a good idea, thanks! You can read it [in this topic](https://steamcommunity.com/workshop/filedetails/discussion/1420955187/1726450077683939616/).
