### ISSUE TITLE
Commerce in industrial areas showing not enough customers

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#39]
Due to the 'lunch hour' feature, I've put some commercial buildings in industrial areas - around lunch time, the configured percentage of cims do appear to be heading to the commerce to get lunch.

However, at all other times, cims in industrial areas are unlikely to visit the shops, causing the 'not enough customers' bubble to be displayed. I've placed the industrial area in a valley quite some distance from the nearest residential zones, so even cims willing to travel to shops are unlikely to visit the rudimentary commerce nestled amidst the industrial area.

If some cims visit commerce for breakfast on way to work, could some of those check for commerce near work and, if found, favor that over commerce near home? Same on way home - some cims could nip to shops near work before commuting home? Assuming those checks would be time consuming, maybe have a cached flag per workplace or district indicating presence of nearby commerce.

**Comment by dymanoid** [comment]
The citizens can already choose the shops near their workplaces when leaving the work building and it's time to go shopping. But I don't think it's a good idea to force the citizens to go shopping near their workplaces in the morning. I'm thinking about changing the 'no customers' behavior. Maybe this building problem should appear much later than by game defaults (e.g. only when a building has no customers for 24h).

**Comment by aubergine10** [comment]
Yes, changing the warning bubble to operate on 24hr average would be much better.

**Comment by Sipke82** [comment]
So if you are going to change the problem notifiction to 24 hours, The "Won'tfix"  label might be incorrect :-)

**Comment by dymanoid** [comment]
The better 'building problem' logic will be implemented in #42.
