### ISSUE TITLE
Use day/night sliders in settings UI

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#45]
The settings UI has grown quite large and I assume it will grow further as the mod matures.

Would it be worth using the combined day/night sliders as seen on the budgets panel? This would allow several of the day/night and start/finish sliders to be merged, reducing amount of sliders in the mod settings.

**Comment by dymanoid** [comment]
I'd like to keep them separate. Instead, when there will be more settings, I'll group them to different tabs to keep the UI clear.
