### ISSUE TITLE
Advanced status in info panels (was: Should students be "going home" at 5am?)

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#48]
Yesterday I noticed, around 5am game time, lots of students driving home. Their college (university) is relatively short drive from where they live.

I suspect they were returning from distant leisure (I had a large amusement park on other side of map) but so far haven't found a way to check where they were coming from (the vanilla routes report tool only shows the remaining part of their journey which is somewhat annoying).

I guess it's just my mind being weird again, like the ill-fated #33 , but with RT active I suddenly feel an increased need to know what my cims are up to (eg. are they on the roads because they just finished a work shift or something else) - such info would help with planning transport routes, etc.

Would it be possible to mod the info panels for cars, cycles and pedestrians to show details about where they're coming from (currently it only shows where they are going to). For example "Was at {previous location}"?

**Comment by dymanoid** [comment]
I like the idea of providing advanced information in the info panels. This is definitely worth implementing!

**Comment by dymanoid** [comment]
This feature is implemented as a stand-alone mod: [Snooper](https://github.com/dymanoid/Snooper).
