### ISSUE TITLE
Too many virtual citizens (was: Most workers teleport to the industries)

### ISSUE THREAD

**Issue by Sipke82** [dymanoid/RealTime#66]
After Rush hour it appears that most works have teleported to the indsutries. Now that the parkingAI of TMPE is working again, these parking lots should be filled with cars....
https://i.snag.gy/XbTvyI.jpg
I use the lowest possible amount of percentages for nightshift and second shift.

**Additional mods**
like 80

**Comment by dymanoid** [comment]
Which setting for virtual citizens are you using?

**Comment by Sipke82** [comment]
Almost all real, i think that is the default setting

**Comment by dymanoid** [comment]
What do I need to do to reproduce this? It doesn't happen with my test game.

**Comment by Sipke82** [comment]
I suspect it has something to do with city size, my city is somewhat large ~130k

**Comment by Sipke82** [comment]
When i set "All citizens are real" i get the traffic and parking i expect, my i5 processor does not fully agree with me though ;-)

**Comment by dymanoid** [comment]
So in fact, you would like to have a level of virtualization between "all real" and current "almost all real" - correct? Currently, "almost all real" means 10% of the citizens are virtual. Maybe we need to make this number depend on the number of currently visible citizen, not just hard-code it as 10%,

**Comment by Sipke82** [comment]
Well the difference in my game is far greater than the 10% 
Around, 35k citizens instances at "Almost Real" and 65k instances at "All real"

**Comment by dymanoid** [comment]
Okay, spotted the issue. You're right, some citizens were made virtual although they shouldn't be.
