### ISSUE TITLE
Add construction effect to RICO buildings

### ISSUE THREAD

**Issue by Sipke82** [dymanoid/RealTime#71]
Add construction effect to RICO buildings. Would be cool to see that large skyscraper being build in a few weeks (#69 )

**Comment by originalfoo** [comment]
Out of scope for RT mod is it not?

It's problem with RICO mod not asking the game to construct buildings, it just instantly spawns them.

Looks like the RICO mod is no longer maintained: https://github.com/AJ3D/Ploppable-RICO

**Comment by Sipke82** [comment]
Well perhaps this is out of scope, and could be an idea for another mod.

I got to the idea due to the fact that growables being plopped using the "plop the growables"mod do show construction, while that mod description says that it should be removed. Thus RT somehow overrides that (which is cool). Thus i was thinking perhaps we can also override the effect of the RICO mod.

Now that I think of it even further, this could even be extended to all plopable buildings.... schools, hospitals etc...

**Comment by dymanoid** [comment]
This is indeed out of scope for **Real Time**. This can be only accomplished by RICO itself. This mod has to enable the "normal" building construction behavior (maybe optional). As for the second idea (slow construction of ploppable service buildings) - this is cool, but out of scope too. This is something for a separate mod (if it's possible at all).
