### ISSUE TITLE
Lights out when sleeping

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#73]
Following on from discussion in #65, I've separated this out in case there's an asset creator or modder that can assist with the following:

> dymanoid: This is a tough one. I'm not an asset editor and have no idea how to control all that 3D stuff. So of course we can list this feature here, but I doubt I can implement it any time soon. A help from some asset editor / Unity3D geek would be highly appreciated.

I suspect @ronyx69 might know how that stuff works as he's done a bunch of mods relating to visual stuff.

Info is required for the code is that toggles building window lights for the day/night cycle.

Simplified summary (eg. ignoring fact that in summer the sunset could occur after sleep time, etc):

* Sunset: Base game turns lights on
* Sleep time: RealTime makes some buildings go dark, because cims are sleeping 
* Wake time: RealTime relights some of those buildings as cims are getting up for work
* Sunrise: Base game turns lights off

Prop lights would be largely unaffected, eg. the red flashing lights at top of skyscrapers, etc. That being said, if code is available to toggle those, I have some ideas for a separate mod that could make use of it :)

**Comment by aubergine10** [comment]
boformer wrote:

> One way I could think of is to replace the illumination texture, but that means all buildings of the same type will turn off their lights at the same time. Performance would also be a concern.
> 
> You could also look into the method that determines if a building has electricity, and then detour that or a method that calls it (no electricity = no lights)

**Comment by aubergine10** [comment]
Other things that cause lights out:

* Power cut
* Daytime
* Building turned off

All those things likely call a function rather than replicating code. I have no idea how to find that in the code though :/

**Comment by aubergine10** [comment]
More from boformer:

Take a look at `CommonBuildingAI.RenderInstance`, especially this line:

    instance.m_dataColor0 = buildingInfo.m_buildingAI.GetColor(buildingID, ref data, Singleton<InfoManager>.instance.CurrentMode);

That one calls `CommonBuildingAI.GetColor` (for normal buildings), which sets the correct color for the building when info view are open (e.g. electricity info view).

But there is also `InfoManager.InfoMode.None` (no overlay open), and it also returns a color!

The first 3 channels (`r`, `g`, `b`) are used for the visible color variation of the building (growable buildings have 4 color variations), but it seems like the alpha channel (`a`) is used to store the electricity value (`0f` for off, `1f` for on):

```
if (ShowConsumption(buildingID, ref data) && data.m_fireIntensity == 0 && flag)
{
    Singleton<ElectricityManager>.instance.CheckElectricity(data.m_position, out bool flag2);
    result.a = ((!flag2 && ElectricityGridRadius() != 0f) ? 0f : 1f);
}
else
{
    result.a = 0f;
}
```

You can see that the lights are always turned off when the building is on fire, or when the building is not active (when `flag` is `false`).

You can also see that before setting alpha to `1f`, `ShowConsumption(buildingID, ref data)` is checked. You could detour that method to return false under certain circumstances to turn off the lights of a particular building! Make sure that your detoured code is efficient!

**Comment by aubergine10** [comment]
Ponder from me: Depending on how the game checks the alpha value, I imagine there's a few bits in there that could store custom info about the building?

For example, could RT use some of the unused bits to store info about which shifts the building is open for? This would allow basically every building to have it's work shifts specified in granular fashion without eating in to the mod persistence limit in saves? There could be general rules that define when buildings of certain types are operational, but the alpha bits could override allowing building-specific customisations to be applied (eg. I can turn off small doctor surgery in evenings/night but leave hospital open 24/7)....

**Comment by aubergine10** [comment]
Just guessing at some possible problems that might arise and what mods could illustrate how to work round them...

For hiding problem indicators: https://steamcommunity.com/sharedfiles/filedetails/?id=561293123

For disabling problems: https://steamcommunity.com/sharedfiles/filedetails/?id=917543381

Couldn't find the source for the mods on github, but I assume it might be included as plain text in the workshop file?

**Comment by aubergine10** [comment]
Ponderance over bit values if that turns out to be viable:

bit | use
--- | ---
1 | electricity on if set
2 | denotes custom open hours (see notes below)
3 | 24/7 building if set, otherwise...
4 | morning shift enabled it set
5 | day shift enabled if set
6 | evening shift enabled if set
7 | night shift enabled if set
8 | weekends enabled if set
...? | I assume it's 16-bit word? could have stuff like "early close on sundays" (common for low commerce in EU)

If a building has custom open hours then bit 2 gets set so that future checks can short-circuit out without having to check a bunch of other bits.

Such setup would allow, for example, a default that oil and ore is open 24/7 but I could set some of those buildings to close at weekends or late night.

**Comment by aubergine10** [comment]
I assume `InfoManager.InfoMode.None` can be queried even when the info view is active? If so, you could potentially create a custom info view....

By default it would show highlight the currently open and currently closed buildings.

But user could select from a list what they want to inspect:

* Currently open vs. closed
* Open 24/7
* Has morning shift (would include 24/7 buildings)
* Has day shift (ditto)
* Has evening shift (...)
* Has night shift
* Weekend vs. weekday (3 building highlight colours = differentiate between: both, weekday, weekend)
* Early close on Sunday

And so on.

**Comment by aubergine10** [comment]
I feel there's perhaps two separate feature requests emerging here:

1. Residential has lights out late at night while sleeping (just like RL!)
2. All other types of building have a defined workshift

On feature 2, that would allow players to do crazy things... For example, I could close some park buildings on weekdays to free up workers for industry or commerce, and then have some industry/commerce shut on weekends to free up workers for parks.

There's probably a load of technical factors I'm not considering so I'll stop rambling for now :)

**Comment by aubergine10** [comment]
Building light overrides was added to Rush Hour 2 mod: https://github.com/PropaneDragon/Rush-Hour-2/commit/afd83ca794c6ebfc8653ac3070a14bab251119e1

**Comment by dymanoid** [comment]
@aubergine10 ...and that causes chaos, when I read the user comments on that mod.

**Comment by aubergine10** [comment]
The update was pushed to Steam on Sat 22nd July, and I've not see any comments on the mod page (or /r/CitiesSkylines) from that time to present about issues with the lights. Are there other places where the mod is being discussed?

Regardless, I was posting more as confirmation that the code mentioned by boformer does seem to work in respect of turning lights on and off.

I'm not sure the somewhat excessive mod config options relating to lighting in the RH2 mod are necessary (a single option would suffice IMO).

**Comment by dymanoid** [comment]
@aubergine10 The **Rush Hour 2** developer quickly reverted the published update, because it caused massive performance drops. People reported 3-5 FPS.

**Comment by aubergine10** [comment]
Performance has been an issue with Rush Hour 2 since inception, and affects many aspects of that mod (eg. see: https://github.com/PropaneDragon/Rush-Hour-2/issues/22 ).

The update with "lights out" was bundled with loads of other stuff, all of which was implemented in ways that caused performance issues, including the lights out bit.

Part of the problem is that RH2 is doing "lights out" for all types of buildings, but also doing a shed load of logic to determine if a building has it's lights out or not - isn't that going to fubar branch predication?

The "lights out but building still on" should only be applied to residential buildings (as turning building off would be non viable due to causing all cims to be evicted).

All other types of buildings should really use the "building turned off" approach (maybe with some override of warning indicators) as that would also prevent deliveries, workers, etc. -- discussed in #78 .

For the residential buildings it should be just a percentage of them (from memory RH2 is actually checking whether the cims in a residence are at home and crazy stuff like that). So once a percentage has the lights turned out (ideally of a time span of one in-game hour for some variance) they just stay off until morning (specifically ~1 hour before day shift starts?).

I assume the game is already retaining lighting state somehow - otherwise all the lights would be flashing on and off all night in vanilla. As long as the function(s) which affect lighting on residences can be found, it should be viable to prevent the lights coming back on at unwanted times.

Note: I'd expect things like power coming back on after a power outage to cause lights to go back on, and I'd be happy for them to stay on until morning in that scenario because I'd be checking all areas of my city for power outages (a power outage will often cause other problems so when checking I've fixed things I tend to look at the lights rather than confusing multi-state warning bubbles).

**Comment by aubergine10** [comment]
To be blunt, the reason I'm asking for these features in RealTime rather that RushHour is that you are consistently finding performant ways to implement features. The graphs in https://github.com/PropaneDragon/Rush-Hour-2/issues/30 exemplify this.

If residential lights out at night can be implemented in a performant manner, my bets are on RealTime being the mod where that will happen. Same with the "turn buildings off during certain shifts" stuff discussed in #78.

**Comment by aubergine10** [comment]
Yesssssssssssssssss!

**Comment by dymanoid** [comment]
@aubergine10, just curious: are you enjoying these _croutons_ in our soup as they are or do we need some salt/pepper?

**Comment by aubergine10** [comment]
The croutons are great, but I think a tweak to the seasoning could make them better. Will create separate issue in morning when I'm a bit more awake.
