### ISSUE TITLE
Using a car

### ISSUE THREAD

**Issue by timapelov** [dymanoid/RealTime#74]
Our community noticed that VERY much dropped the use of the car, compared with the usual (vanilla) game. It's pretty nice for big cities, but still not everyone wants it. And not every city so strongly refuses the car. It would be wonderful to add a button to select the degree of car usage. And Thank you for your wonderful mod and your work!

**Comment by dymanoid** [comment]
I guess this would be better to discuss with that mod's developer, because **Real Time** won't do anything about it. So I'm closing this issue as out of scope.
