### ISSUE TITLE
Bug, Parks are way too busy at night

### ISSUE THREAD

**Issue by Sipke82** [dymanoid/RealTime#76]
Parks are way too busy at night

For example my local zoo, a few bus loads of new people just arrived.

![image](https://user-images.githubusercontent.com/30873812/42967429-7fe1f0b0-8ba0-11e8-85af-59d7c60c5fa7.png)

Local playground:
![image](https://user-images.githubusercontent.com/30873812/42967524-cd810aae-8ba0-11e8-805d-04f3d4c58a6b.png)

And Pierce is going for a jet ski ride 3:30 AM
![image](https://user-images.githubusercontent.com/30873812/42967575-f626bb84-8ba0-11e8-8e37-718985983f82.png)

**Comment by aubergine10** [comment]
I mentioned this in #65, to which dymanoid replied:

> Probably, this can't be fixed. The game simulates citizen's decisions not for all citizens at the same time, but gradually. Let's say it's 8 p.m. and a pensioner decides to walk in a park. It's ok, because pensioners should go home at 9 p.m. But the next time the game checks this pensioner is maybe 11 p.m. or even midnight or later (this depends on the population size). And of course, that poor pensioner will be there until the next decision says "go home now".

**Comment by Sipke82** [comment]
Perhaps, well the mod description screenshots on the workshop suggest that this feature should work. we could of course also update those screen shots ;-)

**Comment by dymanoid** [comment]
Why do you think it's a bug? Citizens are allowed to visit parks at night. It would be a very boring game if we there will be nothing happening all night long.

By the way, the simulation will be completely revised in #57. This will change the way citizens decide where to go and when.

**Comment by Sipke82** [comment]
Well, the mod description states that cims prefer daytime relaxing opposed to nighttime, while there is no difference in park audience between those points of time ...so that seems unintended and thus a bug. 
And in my opinion a nearly quiet city at night is realistic and has his charms. Indeed it shouldn't be too long, that's why we speed up the time after "sleeptime", which works perfectly for that reason.

**Comment by aubergine10** [comment]
My parks are mostly empty at night - as expected. I have sleep time = 11pm, wake time = 6am. My city is currently fairly compact (it fits in an area roughly equivalent to 1 tile) and has small pop (around 2k currently).

What I noticed was that at sleep time and an hour or so later, there were still lots of cims out and about - likely because the game hadn't got round to telling them to go home yet. This irked me because I wanted to use night budget to reduce PT vehicle count, but couldn't because there was a sort of "bed time rush hour" starting at sleep time.

On bigger cities, I assume people will be out even later as the simulation takes longer to tell all the extra people to go to bed, hence people in the park at 3am.

Hopefully the simulation changes will improve both situations. I wonder if it would be possible to affect when/where people go for leisure based on age/wealth? For example, pensioners less likely to be partying at 11pm as they're mostly in bed by 9 or 10pm.

**Comment by dymanoid** [comment]
With #57, the entire citizens' logic was completely revamped. Now, the citizens create plans and schedule their days, not just randomly moving around. It should totally change their behavior, so the park attendance at night should be reduced. This will be available in **RealTime** [version 1.7](https://github.com/dymanoid/RealTime/milestone/5).

**Comment by Sipke82** [comment]
That just sounds awesome, looking forward to the release 😊

**Comment by dymanoid** [comment]
@Sipke82, I would need your feedback on this issue with the new 1.7 version. Do you see an improvement?

**Comment by Sipke82** [comment]
That's quick! Will provide some feedback in the coming days, away from pc now...

**Comment by Sipke82** [comment]
I find that the regular plopable parks are indeed quiet at night. However the park area's like the zoo/amusement park are still very crowded at night.

**Comment by Sipke82** [comment]
it's like 80% citizens/ 20% tourists.
I play at daytime speed 4, night time speed 7. I see a lot of cims starting their zoo visit at like 01:00 AM. Could it be that were late back from work but they insist on going to the zoo?

**Comment by dymanoid** [comment]
Yes, speed 7 is too fast. At that speed, the citizens are just always too late. Try speed 7 at night.

**Comment by aubergine10** [comment]
My city will be hitting it's night time phase in the next session so I'll report back what I see. I run at day speed = 1 and night speed = 6, with low pop cities.

**Comment by dymanoid** [comment]
I slightly improved the citizens scheduling to cope with faster time speeds. Now the citizens can cancel inappropriate activities (e.g. because it's too late) when they are at home (commit ae0a2ea). This is out with the hotfix 1.8.3. Please report if this helps.

**Comment by aubergine10** [comment]
My parks are pretty much empty after sleep time as expected; 1.8.3 hotfix certainly improved things.

**Comment by dymanoid** [comment]
Yes, the tourist AI will be improved in #110. I close this issue.
