### ISSUE TITLE
Will cims still get up prior to 'wake up time' if they need to go to work?

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#77]
I've currently got 'wake up time' set to 6am, assuming my cims need to wake up and go to work at 7am or after. However, side effect is that building constructions is starting way too early (would normally be 7am or 8am).

If I set a later 'wake up time', will it adversely affect early morning shift, etc? (Difficult to tell from inspecting cims on the map, particularly as my city doesn't have much commerce yet).

**Comment by aubergine10** [comment]
The daily schedule has greatly improved things. Will probably take a few days to assess fully as I mostly play with speed slider set to 1 during day time (and long days due to my wake/sleep settings).

**Comment by Sipke82** [comment]
Perhaps it makes sense that construction starts at work start time instead of wake up time. And that construction ends at work end time.

**Comment by dymanoid** [comment]
I'm not sure. A Workshop user posted some time ago, that construction e.g. in NY can be 24/7. In other countries, construction can start very early. So I think it's a good compromise to couple the construction time to the general 'city awake' time.

**Comment by Sipke82** [comment]
True. Seems fine how it is.

**Comment by aubergine10** [comment]
Or just give construction it's own start/end time sliders?

**Comment by aubergine10** [comment]
For me it's working fine as is, my wake time is now 7am and city is behaving much more realistically (from my perspective at least).

Only suggested the separate slider as it seems some players desire construction times that don't correlate to wake/sleep times.
