### ISSUE TITLE
Ability to customise shifts per building

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#78]
I veered off-subject in #73 so splitting in to this separate issue...

**Comment by aubergine10** [comment]
Ponder from me: Depending on how the game checks the alpha value, I imagine there's a few bits in there that could store custom info about the building?

For example, could RT use some of the unused bits to store info about which shifts the building is open for? This would allow basically every building to have it's work shifts specified in granular fashion without eating in to the mod persistence limit in saves? There could be general rules that define when buildings of certain types are operational, but the alpha bits could override allowing building-specific customisations to be applied (eg. I can turn off small doctor surgery in evenings/night but leave hospital open 24/7)....

EDIT: Would need to override anything that changes the alpha value to ensure it doesn't replace the unused bits (ie. set specific bit rather than just 1f), and anything that reads it to check for a specific bit rather than just 1f. (My C# skill level is 'complete noob' so apologies if the preceding sentence is complete gibberish).

**Comment by aubergine10** [comment]
Ponderance over bit values if that turns out to be viable:

bit | use
--- | ---
1 | electricity on if set
2 | if set, building has custom open hours (see notes below)
3 | 24/7 building if set, otherwise...
4 | morning shift enabled it set
5 | day shift enabled if set
6 | evening shift enabled if set
7 | night shift enabled if set
8 | weekends enabled if set
...? | I assume it's 16-bit word? could have stuff like "early close on sundays" (common for low commerce in EU)

If a building has custom open hours then bit 2 gets set so that future checks can short-circuit out without having to check a bunch of other bits.

Such setup would allow, for example, a default that oil and ore is open 24/7 but I could set some of those buildings to close at weekends or late night. Or I could have commerce shut at night, but override a supermarket to be open 24/7. And so on...

**Comment by aubergine10** [comment]
I assume `InfoManager.InfoMode.None` can be queried even when the info view is active? If so, you could potentially create a custom info view....

By default it would highlight the currently open (eg. blue) and currently closed buildings (eg. black).

But user could select from a list what they want to inspect:

* Currently open vs. closed (default when opening info view)
* Open 24/7
* Has morning shift (would include 24/7 buildings)
* Has day shift (ditto)
* Has evening shift (...)
* Has night shift
* Weekend vs. weekday (3 building highlight colours = differentiate between: both, weekday, weekend)
* Early close on Sunday

And so on. This would be incredibly useful, especially if it could be further filtered to building type - eg. I could filter to commerce and look round to ensure that each district has at least one 24/7 open shop (if that's what I want for my city).

**Comment by aubergine10** [comment]
That would allow players to do crazy things... For example, I could close some park buildings on weekdays to free up workers for industry or commerce, and then have some industry/commerce shut on weekends to free up workers for parks.

There's probably a load of technical factors I'm not considering so I'll stop rambling for now :)

**Comment by dymanoid** [comment]
I really don't know if it's a good idea to control each building so precisely. The game provides no exact control over the workers. The customized per-building work shifts only make sense if players can manually assign workers to buildings or control their amount at least. That is impossible with vanilla game. Maybe, this could be implemented in a separate mod. But this is of course out of scope for **Real Time**. Why micro-management?

**Comment by aubergine10** [comment]
Life balance mods affect cims, not businesses. RealTime is already affecting businesses due to the whole work shift thing (and constructions etc). 

If the buildings are being "turned off" (rather than just lights out like residential buildings - #73 ) then that in effect is controlling the workers - the game already has to deal with that situation as users can turn buildings off.

Control over individual shifts would be nice, but not essential. The main things from my perspective are:

1. Is the building open overnight?
2. Is the building open at weekends?
3. If open at weekends, does it close early on Sunday?

While all of those things could be handled macroscopically, doing so would ignore the actual design or purpose of a building. I guesstimate that 60-70% of cases (such as Example 1 below) could be handed by the 3 settings listed above, and 95% of cases could be handled by the extended set of options listed earlier (see Example 2 below). Hence I desire the ability to have at least some building-specific work shift control (mainly for services and leisure, and ideally also industry; but definitely not for residential).

Example 1: I have two commerce buildings - a department store and a supermarket. These are big buildings, essentially landmarks in my city. How do I specify that the supermarket is open 24/7 but the department store isn't (or that the department store also closes early on Sundays)?

Example 2: My home town has a train station that is generally shut during day shift (until recently due to public demand) and night shift. During those periods people have to get train to nearest major station and then get a taxi or bus. I'd love to be able to recreate that in game, although it would need the more fine-grained controls described in earlier comments.

Example 3: Smaller doctors surgeries close at night, forcing cims to seek larger hospitals for A&E.

**Comment by aubergine10** [comment]
Just as cims have a schedule, building should too :)

**Comment by aubergine10** [comment]
In what way are workers and buildings mapped? Does the building have a list of workers, or does each cim have a specified place of work?

I assume the latter, otherwise pedestrian/bicycle/car info panels would have to check all buildings in order to state where a cim works? Is there some way to say "list the workers assigned to this building"? if so, could that list be stored while a building is turned off due to shifts and then later restored? The data would not need to persist saves, as it can be recreated by looking at the cims to see where they work when a game loads?

Regarding production rates, aren't those already affected by shifts? Currently i assume that during shifts the overall productions and consumptions for various resources and goods are just 'reduced' by percentages, but that's still going to take in to account any buildings the player has turned off (and likewise, any buildings the mod would turn off if player configures that building to be closed for whatever shifts).

I can already turn my buildings on and off, but it's cumbersome to do on a daily cycle. Do I pause the game after evening shift and then go round all my low commerce turning them off, every night?

Maybe the on/off thing could be moved to separate mod, but it would need to know what the RT shift settings are in order to know when to turn buildings on and off, and also when those settings change, probably as well as a bunch of other stuff. And it would likely conflict with daily schedules of cims, because those would be calculated without knowledge of the external mod... Which is why I think, the only viable place to implement the feature is in RT itself.

**Comment by dymanoid** [comment]
> Does the building have a list of workers, or does each cim have a specified place of work?

The buildings maintain no worker lists, such lists are always calculated dynamically when needed (e.g. which citizens to send home on demolishing). Each citizen has a work building assignment.

> Regarding production rates, aren't those already affected by shifts?

No, the work shifts are only visual. There is no correlation between work shifts and production rate. The production rate depends only on the building's total worker count. It's odd, but the "closed at Weekend" industrial buildings are still producing goods, even "without" workers. See my explanation above. Otherwise, we'd have had a tsunami of "not enough goods" etc. bubbles on Weekends.

However, there **is** a dependency of a commercial building's "production rate" on the customers number. But the customers aren't workers, they are visitors.

Maintaining a custom list of workers will not solve the problem, because the game would assign the workers in a different way anyway. And what if there is a new work building available and an old one was demolished? etc. etc. It would introduce a risky error source - it would be very difficult to synchronize the "custom lists" with the game's algorithm.

I still think it's something very special. Don't see a real benefit / value in such a feature. **Real Time** could provide an interface for other mods in future, making it possible to get the work shifts etc. But that's really not the thing I want to bother about in the near future.
