### ISSUE TITLE
Make vanilla game events more realistic

### ISSUE THREAD

**Issue by dymanoid** [dymanoid/RealTime#81]
The vanilla game events are somewhat random. Also, their duration doesn't fit good with the slow time progression.
In the mod's settings, there should de an option to make vanilla game events more realistic. Enabled by default.

**Comment by t1a2l** [comment]
@dymanoid - Hi can you also address The Concert DLC - If you pput a concert area there is an event every few minutes. Also I think you can use this DLC's event creator and implement it in RT.

**Comment by Everybodyknows** [comment]
> @dymanoid - Hi can you also address The Concert DLC - If you pput a concert area there is an event every few minutes. Also I think you can use this DLC's event creator and implement it in RT.

Yes it will be nice with "match a day stadium" too.
