### ISSUE TITLE
Citizens growing-up speed

### ISSUE THREAD

**Issue by dymanoid** [dymanoid/RealTime#82]
In the vanilla game, the citizens grow up too fast for the **Real Time**'s speed.
This can be fixed with other mods.
However, if players don't want to use them, there should be a possibility to slow down the citizens' growing-up speed directly in **Real Time**. Maybe detect if other mods do the same thing and automatically deactivate this setting in **Real Time**.

**Comment by aubergine10** [comment]
It's not so much that people don't want to use the other mods, it's more a case that they are cumbersome to configure (usually xml file requiring game restart) and there's not really any visualisation of the changes apparent in game - eg. When is their birthday? How far are they through school? Do they own a car?

Note: There is/was a mod called 'Favourite Cims' that provided some info but it was very kludgy and reduced fps.

**Comment by aubergine10** [comment]
Also, I'd prefer the other mods to generally keep doing what they're doing (lots of stuff outside scope of RT) but let RT handle the rate of "life speed"...

**Comment by Sipke82** [comment]
FYI :

I did some unprecise experiments using the favorites cim mod, i followed a cim for 2 real time days, i set bot awake and sleepspeed at 7, i dont think it matters here.
I use WG Lifecycle balance mod ( https://steamcommunity.com/sharedfiles/filedetails/?id=654707599 )
In the XML you can set a lifespan modifier, which is default set at 3. With that setting one realtime day = 3 life years of a cim.
In my current project i had set this modifier to 9, and indeed one RT-day ~1 lifeyear of a Cim. I remember from the start of this project that at some point i had a university for a while and i would like to proceed to Offices, but it was quite hard for a while to get educated people.... I kinda liked that dynamic, as the game was punishing me for going too fast!

If my suggestion of "month weeks" #75 get implemented, so a year would take 12 weeks.
And that you set the lifespanmodifer inside the lifecylce xml  at 9.
That would mean that 1 year 12x7 = 84 life years (about a complete life).

**Comment by Gordon-Dry** [comment]
I'll try a lifespan modifier of 0.1 then.

**Comment by Sipke82** [comment]
Why would you do that? Lifespanmodifer at 1 will cause that 2.7 RealTime game hours is 1 cim life year... I think youll need a high lifespan modifier......

**Comment by Gordon-Dry** [comment]
Thanks, the desription above was not clear enough then ...

**Comment by Sipke82** [comment]
I measured with dayspeed at 7.... Not sure if that has effect...

But anyways at dayspeed 7 and lifespan modifier at 9. It took 1 RealTime week for 1 year....
I think  that the life speed also has effect on education progress and perhaps other things. So keep that in mind...

**Comment by dymanoid** [comment]
Each **Real Time** day now means approx. 4 months of citizen's life. That means, a full life span of 85 years will last for 255 **Real Time** days. I think this is pretty playable.
