### ISSUE TITLE
Enhanced schedule and work info

### ISSUE THREAD

**Issue by dymanoid** [dymanoid/RealTime#83]
The citizens have now day schedules and work shifts. It would be nice to see this information in the citizen's info panel, like e.g. the **Snooper** mod does for the origin buildings.

**Comment by aubergine10** [comment]
Info panels are getting somewhat cluttered - could a button open a separate "itinerary" panel?

Hastily thrown-together mock-up:

![region capture 24](https://user-images.githubusercontent.com/1386719/43052166-ef14b8ba-8e1a-11e8-900f-cf6daa4f04b8.png)

The colour of the bars at side relate to the building type (green = residential, yellow = industry, cyan = office, blues = commerce, purple = park area, etc). Alternatively it should be viable to get some icons made eg. briefcase = office work, text book = school, bed = sleeping, etc.

Highlighted background indicates what part of the schedule is currently active. Could potentially also show transport if that is known (eg. "Driving to work").

**Comment by dymanoid** [comment]
Interesting idea, but I think the first step should be rather small. Displaying the next scheduled activity in the citizen's info panel should be enough.
