### ISSUE TITLE
Mute empty buildings and parks

### ISSUE THREAD

**Issue by dymanoid** [dymanoid/RealTime#85]
The game always plays a certain building's sound when this building is in the camera view box.
It's odd that an empty school at night still sounds like full-crowded one or there are children voices in an empty bouncy castle park.
So the game shouldn't play any sound for buildings and parks that are empty.
Maybe this can be an independent mod.

**Comment by aubergine10** [comment]
Ambient Sounds Turner mod is long-overdue an update. There's a whole bunch of buildings from recent DLC that it doesn't cover (eg. all the amusement park stuff) + some vehicles too.

**Comment by dymanoid** [comment]
That mod is not really the same thing. I don't want to change sounds, neither to change their volume. It's just a simple thing: building empty --> no building sound; otherwise, default game's behavior.
