### ISSUE TITLE
Better shopping and entertainment building selection

### ISSUE THREAD

**Issue by dymanoid** [dymanoid/RealTime#86]
Currently, when searching for a local building, **Real Time** picks one using the base game filter. It scans the buildings in a building grid from top-left to bottom-right and selects the first matching one.
For a global building search, the game's tool set is used too. This results in absolutely random building selections. This is not realistic.

The building selection filter should include:

- more randomization for local buildings
- age based restrictions (no children in night clubs, even in the daytime!)
- age based preferences (a senior will rather visit a children playground than a bar)
- wealth based preferences (wealthy citizens will go to a high-level bar, poor ones will search for affordable places)
- banned buildings (like e.g. car parks that are erroneously placed in the 'parks' group)

Something else?

**Update**
I decided to not implement these fine restrictions. They only over-complicate the game and could lead to an undesirable effects like less citizens going out: we have no control of what buildings appear (without using mods like **Plop the growables** or **RICO**), thus we shouldn't prevent citizens to visit the buildings when it's good time to relax (good weather, not to late).

The features that will be implemented:

- more randomization on local building search
- building capacity matters
- car parks should be avoided for visiting

**Comment by aubergine10** [comment]
How to classify the buildings? For example, in a leisure district how do you know which buildings are bars and which are slot machines?

Likewise, how to detect carparks (or anything else that's not really a park) deployed as parks?

I've seen numerous carpark "park" assets that even have entertainment accumulation and tourist counts! Parking spaces could potentially be counted, however there are some "actual parks" parks that have quite a lot of parking spaces in them (eg. some are like city gardens with a load of parking space on the side). There's also things like alley "parks" which you would expect to sometimes see people loitering in despite them not being designed for leisure. And there's loads of container "parks" - no parking spaces, just loads of shipping containers, and certainly not somewhere I'd expect cims to want to go.

IMO in addition to automated classification of assets, it would be useful to also have an xml file where specific assets could be classified should automated approach fail. Bonus points if a checkbox on the info panel of buildings can be used to update the xml; eg. I click a park that the mod things valid and toggle the "Leisure destination" checkbox and it gets added to the list of "parks that aren't parks" in the xml?

**Comment by dymanoid** [comment]
> I've seen numerous carpark "park" assets that even have entertainment accumulation and tourist counts! 

That's the thing I'd like to avoid. Residents and tourists should not "visit" those parking buildings.

> it would be useful to also have an xml file where specific assets could be classified

This is a nightmare job to maintain. Look at the assets count in the Workshop. I don't think it's even doable.

**Comment by aubergine10** [comment]
I had a brief browse of the "park" assets in workshop and omg, there are so many "definitely not a park" parks in there. Boats, trains, bridges, lumber mills(!??) the list goes on and on.

Rather than maintaining xml, maybe a UI element on info panel so players can let RT know which of their "park" assets aren't parks (or in case of false positives, let RT know the park is actually a park)?

**Comment by Sipke82** [comment]
Perhaps also the capcity of a building should be taken into account:
This tiny pasta restaurant has 630 incoming paths,
![image](https://user-images.githubusercontent.com/30873812/43153368-6713fcb6-8f71-11e8-80aa-81e83359fad4.png)
and the huge hotel behind it has 200
![image](https://user-images.githubusercontent.com/30873812/43153403-7d20f270-8f71-11e8-99ba-0e93bea874b9.png)

**Comment by dymanoid** [comment]
I decided to not implement those fine restrictions. See issue description for details.
