### ISSUE TITLE
Citizens should enter buildings when it rains

### ISSUE THREAD

**Issue by dymanoid** [dymanoid/RealTime#87]
This feature was introduced in **Rush Hour 2** and seems to be very neat and realistic.

Currently, **Real Time** causes citizens to leave parks and abort tours when it starts raining, but the citizens e.g. hanging around at a school will still be outside.

**Comment by aubergine10** [comment]
Would this cause cims to suddenly rush in to industry, residence, office buildings? Would seem weird.

I can imagine them leaving a crowd attractor to go in to building that's part of same asset, or entering shops or PT stations, but if you had cims suddenly running in to police stations or oil refineries it would seem really weird.

**Comment by dymanoid** [comment]
No, the travelling citizens will not change their destination abruptly. Let's pretend they have umbrellas.
Instead, the citizens hanging around outside of the buildings (leisure, home, schools, medical clinics etc.) should just enter them. Technically, those citizens are already "in buildings" (visiting, at home, at work), but they are just rendered outside for a visual experience.
