### ISSUE TITLE
Chinese localization

### ISSUE THREAD

**Issue by dymanoid** [dymanoid/RealTime#91]
The Chinese localization should be created.
@TOMMIVS, maybe you could help with that? You helped with localization for **Rush Hour 2**, so I thought you could also help for **Real Time**. By the way, you could also try to play with **Real Time**, it has similar features (and even more) but is 5x times faster.

**Comment by TOMMIVS** [comment]
No problem.

**Comment by dymanoid** [comment]
Fixed by #121.
