### ISSUE TITLE
Tents = Hotels?

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#98]
Just noticed that tents (wildlife park asset in Parklife DLC) are treated as parks when in reality they are micro-hotels.

Probably outside scope of RT, but thought I'd ask just in case: Can RT treat tents as hotels, and thus the tourists/cims stay in them overnight and go walkabout during day?

**Comment by Sipke82** [comment]
RT has as the feature that Tourists stay the night in a hotel. I guess it would be cool if tents would be included. 
This feature might need some improvement though, as I've seen dozens of tourists spending the night at a pasta restaurant (also a building from the Tourism buildings). Perhaps the tourists, should confirm if the building has the name "Hotel" or "Tent" in it?

**Comment by dymanoid** [comment]
In Italy, most pizzerias and pasta restaurants have rooms where tourists can stay overnight. I know it because I pretty often visit Italy 😉

I didn't know there are some "tents". I will take a look on that.

**Comment by dymanoid** [comment]
Code investigation shows that this would cause a performance drop when searching for hotels. In the search loop, an additional service needs to be included, as well as an additional check for building AI instance and its class name.

With #100, tourists are allowed to visit parks in the night, so they will visit the "tents" too. However, they won't stay overnight there. I think the performance drop is undesirable at this point, so I decide to not implement this special handling of tents.
