### ISSUE TITLE
Reduced water/sewage/electricity at night when cims are sleeping?

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#99]
Split out from #65 :

At night, I would expect water/sewage/electricity consumption to be much reduced, as many cims are sleeping and many workplaces (particularly farming/forestry which use huge amounts of water in particular) are closed for the night.

I tried setting my night time budget for those things much lower, but ended up with power outages, water shortrages, etc. The vanilla game does some reduction, but perhaps not enough.

> dymanoid: This is something for another mod. There are other mods that change this (e.g. "Realistic Consumption" etc.), so I don't want to make Real Time incompatible with all those.

**Comment by dymanoid** [comment]
I still think it's out of scope for **Real Time**. With the sleep/awake setting, the _night time_ in the game is decoupled from the sunset and sunrise, so any other mod can use this information and change the consumption accordingly.

**Comment by originalfoo** [comment]
I agree, but...

RT is now keeping track of whether a building is empty, how many people are working each shift, when cims are sleeping, etc. Is it not the ideal place to calculate a more accurate energy/water/sewage amount at any given time?

To attempt that level of detail in an external mod would result in duplicate calculations (or at the very least duplicate iterations of the buildings). While I wouldn't expect the resource usage to update every frame - every 30 mins game time would suffice imo - it would still be clunky to implement in external mod.

**Comment by dymanoid** [comment]
@aubergine10 , **Real Time** doesn't track whether buildings are empty. Neither it knows how many people are working each shift (it knows only the percentage). So for this consumption simulation to work, **Real Time** would need to be more detailed. That would automatically mean a huge performance drop (e.g. remember the **Rush Hour II** mod where the developer tried to keep track of the citizens for switching the lights off - that was a nightmare performance issue).

I don't think that the benefit of having such a feature can justify the performance issues (especially for large cities).

For a 'somewhat realistic consumption', there is such a mod already. So my thoughts are - drop it.

**Comment by originalfoo** [comment]
Agreed
